import type { AssetRef, FontFaceDefinition, RuntimeAsset } from "@v-ronpa/contracts";
import type { RuntimeAssetFragment } from "@v-ronpa/asset-registry";
import type { LayeredCharacterPreloadPlan } from "@v-ronpa/app-vn-shell";
import { pixiRuntimeAssetFragment } from "@v-ronpa/runtime-assets-pixi";

// Generated by scripts/generate-assets.mjs. Do not edit by hand.
export const harnessRuntimeAssets = [
    {
      "id": "bg:black",
      "kind": "background",
      "optimizedUri": "/harness/backgrounds/black.png",
      "format": "png",
      "compression": [],
      "lods": [],
      "collisionProxyIds": [],
      "tags": [
        "harness"
      ]
    },
    {
      "id": "bg:classroom",
      "kind": "background",
      "optimizedUri": "/harness/backgrounds/classroom.png",
      "format": "png",
      "compression": [],
      "lods": [],
      "collisionProxyIds": [],
      "tags": [
        "harness"
      ]
    },
    {
      "id": "bg:harness",
      "kind": "background",
      "optimizedUri": "/harness/backgrounds/harness.png",
      "format": "png",
      "compression": [],
      "lods": [],
      "collisionProxyIds": [],
      "tags": [
        "harness"
      ]
    },
    {
      "id": "bg:inner-academy-hall",
      "kind": "background",
      "optimizedUri": "/harness/backgrounds/inner-academy-hall.png",
      "format": "png",
      "compression": [],
      "lods": [],
      "collisionProxyIds": [],
      "tags": [
        "harness"
      ]
    },
    {
      "id": "bg:inner-snow-outskirts",
      "kind": "background",
      "optimizedUri": "/harness/backgrounds/inner-snow-outskirts.png",
      "format": "png",
      "compression": [],
      "lods": [],
      "collisionProxyIds": [],
      "tags": [
        "harness"
      ]
    },
    {
      "id": "bgm:validation-alt",
      "kind": "bgm",
      "optimizedUri": "/harness/media/bgm/bgm-validation-alt.ogg",
      "format": "ogg",
      "compression": [],
      "lods": [],
      "collisionProxyIds": [],
      "tags": [
        "harness"
      ]
    },
    {
      "id": "bgm:validation-extra",
      "kind": "bgm",
      "optimizedUri": "/harness/media/bgm/bgm-validation-extra.ogg",
      "format": "ogg",
      "compression": [],
      "lods": [],
      "collisionProxyIds": [],
      "tags": [
        "harness"
      ]
    },
    {
      "id": "bgm:validation-layer",
      "kind": "bgm",
      "optimizedUri": "/harness/media/bgm/bgm-validation-layer.ogg",
      "format": "ogg",
      "compression": [],
      "lods": [],
      "collisionProxyIds": [],
      "tags": [
        "harness"
      ]
    },
    {
      "id": "bgm:validation-main",
      "kind": "bgm",
      "optimizedUri": "/harness/media/bgm/bgm-validation-main.ogg",
      "format": "ogg",
      "compression": [],
      "lods": [],
      "collisionProxyIds": [],
      "tags": [
        "harness"
      ]
    },
    {
      "id": "bleep:dialogue-default",
      "kind": "bleep",
      "optimizedUri": "/harness/media/bleep/dialogue-default.ogg",
      "format": "ogg",
      "compression": [],
      "lods": [],
      "collisionProxyIds": [],
      "tags": [
        "harness"
      ]
    },
    {
      "id": "bleep:dialogue-felix",
      "kind": "bleep",
      "optimizedUri": "/harness/media/bleep/dialogue-felix.ogg",
      "format": "ogg",
      "compression": [],
      "lods": [],
      "collisionProxyIds": [],
      "tags": [
        "harness"
      ]
    },
    {
      "id": "Ema",
      "kind": "character-pack",
      "optimizedUri": "/harness/characters/Ema/character.json",
      "format": "json",
      "compression": [],
      "lods": [],
      "collisionProxyIds": [],
      "tags": [
        "harness"
      ]
    },
    {
      "id": "font:rich-serif",
      "kind": "font",
      "optimizedUri": "/harness/fonts/rich-serif.ttf",
      "format": "ttf",
      "compression": [],
      "lods": [],
      "collisionProxyIds": [],
      "tags": [
        "harness"
      ]
    },
    {
      "id": "model:academy-hall",
      "kind": "glb",
      "optimizedUri": "/harness/models/academy-hall.gltf",
      "format": "gltf",
      "compression": [],
      "lods": [],
      "collisionProxyIds": [],
      "tags": [
        "harness"
      ]
    },
    {
      "id": "model:classroom",
      "kind": "glb",
      "optimizedUri": "/harness/models/classroom.gltf",
      "format": "gltf",
      "compression": [],
      "lods": [],
      "collisionProxyIds": [],
      "tags": [
        "harness"
      ]
    },
    {
      "id": "model:props-case-file",
      "kind": "glb",
      "optimizedUri": "/harness/models/props-case-file.gltf",
      "format": "gltf",
      "compression": [],
      "lods": [],
      "collisionProxyIds": [],
      "tags": [
        "harness"
      ]
    },
    {
      "id": "model:props-door",
      "kind": "glb",
      "optimizedUri": "/harness/models/props-door.gltf",
      "format": "gltf",
      "compression": [],
      "lods": [],
      "collisionProxyIds": [],
      "tags": [
        "harness"
      ]
    },
    {
      "id": "sfx:knock-door",
      "kind": "sfx",
      "optimizedUri": "/harness/media/sfx/knock-door.ogg",
      "format": "ogg",
      "compression": [],
      "lods": [],
      "collisionProxyIds": [],
      "tags": [
        "harness"
      ]
    },
    {
      "id": "sfx:rain-inside-car-loop",
      "kind": "sfx",
      "optimizedUri": "/harness/media/sfx/rain-inside-car-loop.ogg",
      "format": "ogg",
      "compression": [],
      "lods": [],
      "collisionProxyIds": [],
      "tags": [
        "harness"
      ]
    },
    {
      "id": "sfx:shock-fadeout",
      "kind": "sfx",
      "optimizedUri": "/harness/media/sfx/shock-fadeout.ogg",
      "format": "ogg",
      "compression": [],
      "lods": [],
      "collisionProxyIds": [],
      "tags": [
        "harness"
      ]
    },
    {
      "id": "texture:evidence:keycard-thumbnail",
      "kind": "texture",
      "optimizedUri": "/harness/thumbnails/evidence-keycard.png",
      "format": "png",
      "compression": [],
      "lods": [],
      "collisionProxyIds": [],
      "tags": [
        "harness"
      ]
    },
    {
      "id": "texture:item:notebook-thumbnail",
      "kind": "texture",
      "optimizedUri": "/harness/thumbnails/item-notebook.png",
      "format": "png",
      "compression": [],
      "lods": [],
      "collisionProxyIds": [],
      "tags": [
        "harness"
      ]
    },
    {
      "id": "video:validation-intro",
      "kind": "video",
      "optimizedUri": "/harness/media/video/movie-validation-intro.mp4",
      "format": "mp4",
      "compression": [],
      "lods": [],
      "collisionProxyIds": [],
      "tags": [
        "harness"
      ]
    },
    {
      "id": "voice:zh:0102Adv03_Ema001",
      "kind": "voice",
      "optimizedUri": "/harness/media/voice/zh/0102Adv03_Ema001.ogg",
      "format": "ogg",
      "compression": [],
      "lods": [],
      "collisionProxyIds": [],
      "tags": [
        "harness"
      ]
    },
    {
      "id": "voice:zh:0102Adv03_Ema002",
      "kind": "voice",
      "optimizedUri": "/harness/media/voice/zh/0102Adv03_Ema002.ogg",
      "format": "ogg",
      "compression": [],
      "lods": [],
      "collisionProxyIds": [],
      "tags": [
        "harness"
      ]
    },
    {
      "id": "voice:zh:0102Adv03_Ema003",
      "kind": "voice",
      "optimizedUri": "/harness/media/voice/zh/0102Adv03_Ema003.ogg",
      "format": "ogg",
      "compression": [],
      "lods": [],
      "collisionProxyIds": [],
      "tags": [
        "harness"
      ]
    },
    {
      "id": "voice:zh:0102Adv03_Ema004",
      "kind": "voice",
      "optimizedUri": "/harness/media/voice/zh/0102Adv03_Ema004.ogg",
      "format": "ogg",
      "compression": [],
      "lods": [],
      "collisionProxyIds": [],
      "tags": [
        "harness"
      ]
    },
    {
      "id": "voice:zh:0102Adv03_Margo001",
      "kind": "voice",
      "optimizedUri": "/harness/media/voice/zh/0102Adv03_Margo001.ogg",
      "format": "ogg",
      "compression": [],
      "lods": [],
      "collisionProxyIds": [],
      "tags": [
        "harness"
      ]
    },
    {
      "id": "voice:zh:0102Adv03_Margo002",
      "kind": "voice",
      "optimizedUri": "/harness/media/voice/zh/0102Adv03_Margo002.ogg",
      "format": "ogg",
      "compression": [],
      "lods": [],
      "collisionProxyIds": [],
      "tags": [
        "harness"
      ]
    },
    {
      "id": "voice:zh:0102Adv03_Margo003",
      "kind": "voice",
      "optimizedUri": "/harness/media/voice/zh/0102Adv03_Margo003.ogg",
      "format": "ogg",
      "compression": [],
      "lods": [],
      "collisionProxyIds": [],
      "tags": [
        "harness"
      ]
    },
    {
      "id": "voice:zh:0102Adv03_Margo004",
      "kind": "voice",
      "optimizedUri": "/harness/media/voice/zh/0102Adv03_Margo004.ogg",
      "format": "ogg",
      "compression": [],
      "lods": [],
      "collisionProxyIds": [],
      "tags": [
        "harness"
      ]
    },
    {
      "id": "voice:zh:0102Adv03_Sherry001",
      "kind": "voice",
      "optimizedUri": "/harness/media/voice/zh/0102Adv03_Sherry001.ogg",
      "format": "ogg",
      "compression": [],
      "lods": [],
      "collisionProxyIds": [],
      "tags": [
        "harness"
      ]
    },
    {
      "id": "voice:zh:0102Adv03_Sherry002",
      "kind": "voice",
      "optimizedUri": "/harness/media/voice/zh/0102Adv03_Sherry002.ogg",
      "format": "ogg",
      "compression": [],
      "lods": [],
      "collisionProxyIds": [],
      "tags": [
        "harness"
      ]
    },
    {
      "id": "voice:zh:0102Adv03_Sherry003",
      "kind": "voice",
      "optimizedUri": "/harness/media/voice/zh/0102Adv03_Sherry003.ogg",
      "format": "ogg",
      "compression": [],
      "lods": [],
      "collisionProxyIds": [],
      "tags": [
        "harness"
      ]
    },
    {
      "id": "voice:zh:0102Adv03_Sherry004",
      "kind": "voice",
      "optimizedUri": "/harness/media/voice/zh/0102Adv03_Sherry004.ogg",
      "format": "ogg",
      "compression": [],
      "lods": [],
      "collisionProxyIds": [],
      "tags": [
        "harness"
      ]
    },
    {
      "id": "voice:zh:0102Adv04_Ema001",
      "kind": "voice",
      "optimizedUri": "/harness/media/voice/zh/0102Adv04_Ema001.ogg",
      "format": "ogg",
      "compression": [],
      "lods": [],
      "collisionProxyIds": [],
      "tags": [
        "harness"
      ]
    },
    {
      "id": "voice:zh:0102Adv04_Ema002",
      "kind": "voice",
      "optimizedUri": "/harness/media/voice/zh/0102Adv04_Ema002.ogg",
      "format": "ogg",
      "compression": [],
      "lods": [],
      "collisionProxyIds": [],
      "tags": [
        "harness"
      ]
    },
    {
      "id": "voice:zh:0102Adv04_Ema003",
      "kind": "voice",
      "optimizedUri": "/harness/media/voice/zh/0102Adv04_Ema003.ogg",
      "format": "ogg",
      "compression": [],
      "lods": [],
      "collisionProxyIds": [],
      "tags": [
        "harness"
      ]
    },
    {
      "id": "voice:zh:0102Adv04_Ema004",
      "kind": "voice",
      "optimizedUri": "/harness/media/voice/zh/0102Adv04_Ema004.ogg",
      "format": "ogg",
      "compression": [],
      "lods": [],
      "collisionProxyIds": [],
      "tags": [
        "harness"
      ]
    },
    {
      "id": "voice:zh:0102Adv04_Margo001",
      "kind": "voice",
      "optimizedUri": "/harness/media/voice/zh/0102Adv04_Margo001.ogg",
      "format": "ogg",
      "compression": [],
      "lods": [],
      "collisionProxyIds": [],
      "tags": [
        "harness"
      ]
    },
    {
      "id": "voice:zh:0102Adv04_Margo002",
      "kind": "voice",
      "optimizedUri": "/harness/media/voice/zh/0102Adv04_Margo002.ogg",
      "format": "ogg",
      "compression": [],
      "lods": [],
      "collisionProxyIds": [],
      "tags": [
        "harness"
      ]
    },
    {
      "id": "voice:zh:0102Adv04_Margo003",
      "kind": "voice",
      "optimizedUri": "/harness/media/voice/zh/0102Adv04_Margo003.ogg",
      "format": "ogg",
      "compression": [],
      "lods": [],
      "collisionProxyIds": [],
      "tags": [
        "harness"
      ]
    },
    {
      "id": "voice:zh:0102Adv04_Margo004",
      "kind": "voice",
      "optimizedUri": "/harness/media/voice/zh/0102Adv04_Margo004.ogg",
      "format": "ogg",
      "compression": [],
      "lods": [],
      "collisionProxyIds": [],
      "tags": [
        "harness"
      ]
    },
    {
      "id": "voice:zh:0102Adv04_Sherry001",
      "kind": "voice",
      "optimizedUri": "/harness/media/voice/zh/0102Adv04_Sherry001.ogg",
      "format": "ogg",
      "compression": [],
      "lods": [],
      "collisionProxyIds": [],
      "tags": [
        "harness"
      ]
    },
    {
      "id": "voice:zh:0102Adv04_Sherry002",
      "kind": "voice",
      "optimizedUri": "/harness/media/voice/zh/0102Adv04_Sherry002.ogg",
      "format": "ogg",
      "compression": [],
      "lods": [],
      "collisionProxyIds": [],
      "tags": [
        "harness"
      ]
    },
    {
      "id": "voice:zh:0102Adv04_Sherry003",
      "kind": "voice",
      "optimizedUri": "/harness/media/voice/zh/0102Adv04_Sherry003.ogg",
      "format": "ogg",
      "compression": [],
      "lods": [],
      "collisionProxyIds": [],
      "tags": [
        "harness"
      ]
    },
    {
      "id": "voice:zh:0102Adv04_Sherry004",
      "kind": "voice",
      "optimizedUri": "/harness/media/voice/zh/0102Adv04_Sherry004.ogg",
      "format": "ogg",
      "compression": [],
      "lods": [],
      "collisionProxyIds": [],
      "tags": [
        "harness"
      ]
    },
    {
      "id": "voice:zh:voice_validation_0001",
      "kind": "voice",
      "optimizedUri": "/harness/media/voice/zh/voice_validation_0001.ogg",
      "format": "ogg",
      "compression": [],
      "lods": [],
      "collisionProxyIds": [],
      "tags": [
        "harness"
      ]
    }
  ] satisfies RuntimeAsset[];

export const harnessFontFaces = [
    {
      "id": "font:serif",
      "family": "V Ronpa Rich Serif",
      "sourceRef": "font:rich-serif",
      "weight": "400",
      "style": "normal"
    }
  ] satisfies FontFaceDefinition[];

export const harnessRuntimeAssetFragments = [pixiRuntimeAssetFragment] satisfies RuntimeAssetFragment[];

export const harnessScriptMetadataByPath = {
    "harness/harness-showcase.nani": {
      "scriptRevision": "sha256:0b482f4f9b8776fb36acc7c85bf90db4426966d72d858cabc6d36fe3a2984ac7",
      "assetRefs": [
        {
          "id": "bg:black",
          "kind": "background",
          "tags": []
        },
        {
          "id": "bg:classroom",
          "kind": "background",
          "tags": []
        },
        {
          "id": "bg:harness",
          "kind": "background",
          "tags": []
        },
        {
          "id": "bg:inner-academy-hall",
          "kind": "background",
          "tags": []
        },
        {
          "id": "bg:inner-snow-outskirts",
          "kind": "background",
          "tags": []
        },
        {
          "id": "bgm:validation-alt",
          "kind": "bgm",
          "tags": []
        },
        {
          "id": "bgm:validation-layer",
          "kind": "bgm",
          "tags": []
        },
        {
          "id": "bgm:validation-main",
          "kind": "bgm",
          "tags": []
        },
        {
          "id": "Ema",
          "kind": "character-pack",
          "tags": []
        },
        {
          "id": "sfx:knock-door",
          "kind": "sfx",
          "tags": []
        },
        {
          "id": "sfx:rain-inside-car-loop",
          "kind": "sfx",
          "tags": []
        },
        {
          "id": "voice:zh:0102Adv03_Ema001",
          "kind": "voice",
          "tags": []
        },
        {
          "id": "voice:zh:0102Adv03_Ema002",
          "kind": "voice",
          "tags": []
        },
        {
          "id": "voice:zh:0102Adv03_Ema003",
          "kind": "voice",
          "tags": []
        },
        {
          "id": "voice:zh:0102Adv03_Ema004",
          "kind": "voice",
          "tags": []
        },
        {
          "id": "voice:zh:0102Adv03_Margo001",
          "kind": "voice",
          "tags": []
        },
        {
          "id": "voice:zh:0102Adv03_Margo002",
          "kind": "voice",
          "tags": []
        },
        {
          "id": "voice:zh:0102Adv03_Margo003",
          "kind": "voice",
          "tags": []
        },
        {
          "id": "voice:zh:0102Adv03_Margo004",
          "kind": "voice",
          "tags": []
        },
        {
          "id": "voice:zh:0102Adv03_Sherry001",
          "kind": "voice",
          "tags": []
        },
        {
          "id": "voice:zh:0102Adv03_Sherry002",
          "kind": "voice",
          "tags": []
        },
        {
          "id": "voice:zh:0102Adv03_Sherry003",
          "kind": "voice",
          "tags": []
        },
        {
          "id": "voice:zh:0102Adv03_Sherry004",
          "kind": "voice",
          "tags": []
        },
        {
          "id": "voice:zh:0102Adv04_Ema001",
          "kind": "voice",
          "tags": []
        },
        {
          "id": "voice:zh:0102Adv04_Ema002",
          "kind": "voice",
          "tags": []
        },
        {
          "id": "voice:zh:0102Adv04_Ema003",
          "kind": "voice",
          "tags": []
        },
        {
          "id": "voice:zh:0102Adv04_Ema004",
          "kind": "voice",
          "tags": []
        },
        {
          "id": "voice:zh:0102Adv04_Margo001",
          "kind": "voice",
          "tags": []
        },
        {
          "id": "voice:zh:0102Adv04_Margo002",
          "kind": "voice",
          "tags": []
        },
        {
          "id": "voice:zh:0102Adv04_Margo003",
          "kind": "voice",
          "tags": []
        },
        {
          "id": "voice:zh:0102Adv04_Margo004",
          "kind": "voice",
          "tags": []
        },
        {
          "id": "voice:zh:0102Adv04_Sherry001",
          "kind": "voice",
          "tags": []
        },
        {
          "id": "voice:zh:0102Adv04_Sherry002",
          "kind": "voice",
          "tags": []
        },
        {
          "id": "voice:zh:0102Adv04_Sherry003",
          "kind": "voice",
          "tags": []
        },
        {
          "id": "voice:zh:0102Adv04_Sherry004",
          "kind": "voice",
          "tags": []
        }
      ],
      "characterPreloadPlan": [
        {
          "characterId": "Ema",
          "appearanceExpressions": [
            "",
            "Pensive1",
            "Pensive1,ArmR3",
            "Pensive1,ArmR3,ArmR4",
            "Pensive1,ArmR4,Angle01/Head01/Facial01/Mouth01>Mouth01_Smile_Open",
            "Pensive1,ArmR4,Angle01/Head01/Facial01/Sweat01+Sweat01_01",
            "Pensive1,ArmR4,Angle01/Head01/Facial01/Sweat01+Sweat01_01,Angle01/Head01/Facial01/Sweat01-"
          ]
        }
      ]
    }
  } satisfies Record<string, { scriptRevision: string; assetRefs: AssetRef[]; characterPreloadPlan: LayeredCharacterPreloadPlan }>;
