import type { AssetDefinition, AssetId } from "@v-ronpa/contracts";

// Generated by scripts/generate-assets.mjs. Do not edit by hand.
export const harnessAssets = [
    {
      "id": "bg/black",
      "uri": "assets/bg/black.png",
      "mimeType": "image/png"
    },
    {
      "id": "bg/classroom",
      "uri": "assets/bg/classroom.png",
      "mimeType": "image/png"
    },
    {
      "id": "bg/inner/academy-hall",
      "uri": "assets/bg/inner/academy-hall.png",
      "mimeType": "image/png"
    },
    {
      "id": "bg/inner/snow-outskirts",
      "uri": "assets/bg/inner/snow-outskirts.png",
      "mimeType": "image/png"
    },
    {
      "id": "bg/showcase",
      "uri": "assets/bg/showcase.png",
      "mimeType": "image/png"
    },
    {
      "id": "bgm/validation-alt",
      "uri": "assets/bgm/validation-alt.ogg",
      "mimeType": "audio/ogg"
    },
    {
      "id": "bgm/validation-layer",
      "uri": "assets/bgm/validation-layer.ogg",
      "mimeType": "audio/ogg"
    },
    {
      "id": "bgm/validation-main",
      "uri": "assets/bgm/validation-main.ogg",
      "mimeType": "audio/ogg"
    },
    {
      "id": "bleep/dialogue-default",
      "uri": "assets/bleep/dialogue-default.ogg",
      "mimeType": "audio/ogg"
    },
    {
      "id": "bleep/dialogue-felix",
      "uri": "assets/bleep/dialogue-felix.ogg",
      "mimeType": "audio/ogg"
    },
    {
      "id": "char/ema",
      "uri": "assets/char/ema/character.json",
      "mimeType": "application/json"
    },
    {
      "id": "font/rich-serif",
      "uri": "assets/font/rich-serif.ttf",
      "mimeType": "font/ttf"
    },
    {
      "id": "model/academy-hall",
      "uri": "assets/model/academy-hall.gltf",
      "mimeType": "model/gltf+json"
    },
    {
      "id": "model/classroom",
      "uri": "assets/model/classroom.gltf",
      "mimeType": "model/gltf+json"
    },
    {
      "id": "sfx/knock-door",
      "uri": "assets/sfx/knock-door.ogg",
      "mimeType": "audio/ogg"
    },
    {
      "id": "sfx/rain-inside-car-loop",
      "uri": "assets/sfx/rain-inside-car-loop.ogg",
      "mimeType": "audio/ogg"
    },
    {
      "id": "sfx/shock-fadeout",
      "uri": "assets/sfx/shock-fadeout.ogg",
      "mimeType": "audio/ogg"
    },
    {
      "id": "thumb/evidence-keycard",
      "uri": "assets/thumb/evidence-keycard.png",
      "mimeType": "image/png"
    },
    {
      "id": "video/validation-intro",
      "uri": "assets/video/validation-intro.mp4",
      "mimeType": "video/mp4"
    },
    {
      "id": "voice/zh/0102-adv03-ema001",
      "uri": "assets/voice/zh/0102-adv03-ema001.ogg",
      "mimeType": "audio/ogg"
    },
    {
      "id": "voice/zh/0102-adv03-ema002",
      "uri": "assets/voice/zh/0102-adv03-ema002.ogg",
      "mimeType": "audio/ogg"
    },
    {
      "id": "voice/zh/0102-adv03-ema003",
      "uri": "assets/voice/zh/0102-adv03-ema003.ogg",
      "mimeType": "audio/ogg"
    },
    {
      "id": "voice/zh/0102-adv03-ema004",
      "uri": "assets/voice/zh/0102-adv03-ema004.ogg",
      "mimeType": "audio/ogg"
    },
    {
      "id": "voice/zh/0102-adv03-margo001",
      "uri": "assets/voice/zh/0102-adv03-margo001.ogg",
      "mimeType": "audio/ogg"
    },
    {
      "id": "voice/zh/0102-adv03-margo002",
      "uri": "assets/voice/zh/0102-adv03-margo002.ogg",
      "mimeType": "audio/ogg"
    },
    {
      "id": "voice/zh/0102-adv03-margo003",
      "uri": "assets/voice/zh/0102-adv03-margo003.ogg",
      "mimeType": "audio/ogg"
    },
    {
      "id": "voice/zh/0102-adv03-margo004",
      "uri": "assets/voice/zh/0102-adv03-margo004.ogg",
      "mimeType": "audio/ogg"
    },
    {
      "id": "voice/zh/0102-adv03-sherry001",
      "uri": "assets/voice/zh/0102-adv03-sherry001.ogg",
      "mimeType": "audio/ogg"
    },
    {
      "id": "voice/zh/0102-adv03-sherry002",
      "uri": "assets/voice/zh/0102-adv03-sherry002.ogg",
      "mimeType": "audio/ogg"
    },
    {
      "id": "voice/zh/0102-adv03-sherry003",
      "uri": "assets/voice/zh/0102-adv03-sherry003.ogg",
      "mimeType": "audio/ogg"
    },
    {
      "id": "voice/zh/0102-adv03-sherry004",
      "uri": "assets/voice/zh/0102-adv03-sherry004.ogg",
      "mimeType": "audio/ogg"
    },
    {
      "id": "voice/zh/0102-adv04-ema001",
      "uri": "assets/voice/zh/0102-adv04-ema001.ogg",
      "mimeType": "audio/ogg"
    },
    {
      "id": "voice/zh/0102-adv04-ema002",
      "uri": "assets/voice/zh/0102-adv04-ema002.ogg",
      "mimeType": "audio/ogg"
    },
    {
      "id": "voice/zh/0102-adv04-ema003",
      "uri": "assets/voice/zh/0102-adv04-ema003.ogg",
      "mimeType": "audio/ogg"
    },
    {
      "id": "voice/zh/0102-adv04-ema004",
      "uri": "assets/voice/zh/0102-adv04-ema004.ogg",
      "mimeType": "audio/ogg"
    },
    {
      "id": "voice/zh/0102-adv04-margo001",
      "uri": "assets/voice/zh/0102-adv04-margo001.ogg",
      "mimeType": "audio/ogg"
    },
    {
      "id": "voice/zh/0102-adv04-margo002",
      "uri": "assets/voice/zh/0102-adv04-margo002.ogg",
      "mimeType": "audio/ogg"
    },
    {
      "id": "voice/zh/0102-adv04-margo003",
      "uri": "assets/voice/zh/0102-adv04-margo003.ogg",
      "mimeType": "audio/ogg"
    },
    {
      "id": "voice/zh/0102-adv04-margo004",
      "uri": "assets/voice/zh/0102-adv04-margo004.ogg",
      "mimeType": "audio/ogg"
    },
    {
      "id": "voice/zh/0102-adv04-sherry001",
      "uri": "assets/voice/zh/0102-adv04-sherry001.ogg",
      "mimeType": "audio/ogg"
    },
    {
      "id": "voice/zh/0102-adv04-sherry002",
      "uri": "assets/voice/zh/0102-adv04-sherry002.ogg",
      "mimeType": "audio/ogg"
    },
    {
      "id": "voice/zh/0102-adv04-sherry003",
      "uri": "assets/voice/zh/0102-adv04-sherry003.ogg",
      "mimeType": "audio/ogg"
    },
    {
      "id": "voice/zh/0102-adv04-sherry004",
      "uri": "assets/voice/zh/0102-adv04-sherry004.ogg",
      "mimeType": "audio/ogg"
    },
    {
      "id": "voice/zh/voice-validation-0001",
      "uri": "assets/voice/zh/voice-validation-0001.ogg",
      "mimeType": "audio/ogg"
    }
  ] satisfies AssetDefinition[];

export const harnessCharacterAssetIdByCharacterId = {
    "Ema": "char/ema"
  } satisfies Record<string, AssetId>;
