import type { AssetRequirement, VnEntryDef, VnRuntimeScriptCatalog, VnRuntimeScriptSource } from "@v-ronpa/contracts";
import type { LayeredCharacterPreloadPlan } from "@v-ronpa/layered-character";

// Generated by scripts/generate-assets.mjs. Do not edit by hand.
export const gameAVnEntryLocator = {
    "id": "vn:game-a-main",
    "initialScriptPath": "game-a/opening.nani",
    "startLabel": "Start"
  } as const satisfies Pick<VnEntryDef, "id" | "initialScriptPath" | "startLabel">;

export const gameAScriptMetadataByPath = {
    "game-a/chapter-02.nani": {
      "scriptRevision": "sha256:3fa3677c80979db90ea34241c3ce106d3b86716228b8b56a8bfe21a5fbd9a1ad",
      "requirements": [
        {
          "id": "char/alice",
          "capability": "json"
        }
      ],
      "characterPreloadPlan": [
        {
          "characterId": "alice",
          "appearanceExpressions": [
            "eye0,mouth1,armR0,armL0",
            "eye0,mouth1,armR1,armL0",
            "eye0,mouth3,armR2,armL0",
            "eye0,mouth5,armR0,armL0",
            "eye1,mouth1,armR1,armL0",
            "eye1,mouth2,armR4,armL0",
            "eye1,mouth6,armR4,armL0",
            "eye3,mouth3,armR0,armL2",
            "eye4,mouth2,armR0,armL2",
            "eye4,mouth3,armR0,armL2",
            "eye4,mouth4,armR0,armL5"
          ]
        }
      ]
    },
    "game-a/opening.nani": {
      "scriptRevision": "sha256:9dbcce75263cc5b75501f3451012eac4b3dca678d5e2a59f78fd261e7ef15a5e",
      "requirements": [
        {
          "id": "bg/home",
          "capability": "image"
        },
        {
          "id": "bgm/dead-fish-riffle",
          "capability": "audio"
        },
        {
          "id": "char/alice",
          "capability": "json"
        },
        {
          "id": "sfx/gentle-rain-loop",
          "capability": "audio"
        },
        {
          "id": "sfx/glug-glug-glug",
          "capability": "audio"
        },
        {
          "id": "sfx/noise-6hz",
          "capability": "audio"
        }
      ],
      "characterPreloadPlan": [
        {
          "characterId": "alice",
          "appearanceExpressions": [
            "",
            "eye1,mouth3,armR4",
            "eye2,mouth2,armR0,armL0",
            "eye4,mouth4,armR2,armL5"
          ]
        }
      ]
    }
  } satisfies Record<string, { scriptRevision: string; requirements: AssetRequirement[]; characterPreloadPlan: LayeredCharacterPreloadPlan }>;

export const gameAScriptSourcesByPath = {
    "game-a/chapter-02.nani": {
      "scriptPath": "game-a/chapter-02.nani",
      "sourceText": "#Start\n@charTone rain\n@char alice.eye1,mouth1,armR1,armL0 pos:50 wait!\nAlice: 这还差不多。跟紧一点，别又站在雨里发呆。\nnar: 她把伞抬高了一些，刚好让我们都能看见前面的路。\n@char alice.eye4,mouth4,armR0,armL5 pos:50 wait!\nAlice: 先说好，到了店里不许挑半天。妈妈只让我们买牛奶。\nnar: 我问她，既然只是买牛奶，为什么出门前还特意换了双不怕水的鞋。\n@char alice.eye3,mouth3,armR0,armL2 pos:50 wait!\nAlice: 因为我知道某个人一定会踩遍路上每一个水坑。\nAlice: 尤其是那种看起来很浅，实际上能把袜子整个灌满的。\n@char alice.eye0,mouth5,armR0,armL0 pos:50 wait!\nnar: 她说得像一位经验丰富的灾害预报员，却还是把伞更多地偏向了我这边。\nAlice: 你笑什么？我只是不想回去以后听你打喷嚏。\n@char alice.eye1,mouth2,armR4,armL0 pos:50 wait!\nAlice: 而且你要是真感冒了，最后被妈妈叫去端热水的人还是我。\nnar: 我点点头，郑重保证接下来一步也不会踩错。\n@char alice.eye4,mouth3,armR0,armL2 pos:50 wait!\nAlice: 停。你脚边那个就是。\nnar: 鞋尖在水坑边缘悬了一瞬。我收回脚，雨滴随即替我在水面踩出密密麻麻的波纹。\n@char alice.eye0,mouth1,armR1,armL0 pos:50 wait!\nAlice: 看吧。没有我，你走不到街口就会宣布全军覆没。\nnar: 她的语气得意得过分。我决定转移话题，问她准备买哪一种牛奶。\n@char alice.eye4,mouth4,armR0,armL5 pos:50 wait!\nAlice: 原味。购物清单上写得很清楚，原、味、牛、奶。\nnar: 我提醒她，冰柜最上层通常还会放草莓味和巧克力味。\n@char alice.eye1,mouth6,armR4,armL0 pos:50 wait!\nAlice: ……如果巧克力味刚好在打折，也不是不能顺便看一眼。\nnar: 雨声忽然变得轻快起来。也许只是因为她终于承认，这趟出门并不完全是为了完成任务。\n@char alice.eye4,mouth2,armR0,armL2 pos:50 wait!\nAlice: 但是只能看一眼。你不要露出那种已经准备搬空冰柜的表情。\nnar: 我说我脸上只有对生活最朴素的期待。\n@char alice.eye0,mouth3,armR2,armL0 pos:50 wait!\nAlice: 那就把你的期待收好，先过马路。\nnar: 她伸手挡在我身前，等一辆溅着水花的车驶过去，才带着我踏进斑马线。\n@char alice.eye0,mouth1,armR0,armL0 pos:50 wait!\nnar: 我们挤在同一把伞下向亮着灯的街角走去。雨还没有停，但这条路已经没有刚才那么漫长了。\n@stopSfx group:rain fade:0.8\n@stopBgm group:music fade:0.8\n@end\n",
      "scriptRevision": "sha256:3fa3677c80979db90ea34241c3ce106d3b86716228b8b56a8bfe21a5fbd9a1ad"
    },
    "game-a/opening.nani": {
      "scriptPath": "game-a/opening.nani",
      "sourceText": "#Start\n@hideUI dialog\n@sfx sfx/noise-6hz group:noise volume:0.3 loop!\n\n@cue 转眼之间，爱丽丝也跟着跳了下去\n@cue 压根没有想过自己以后该怎样出来\n@cue 要么这口井实在太深，要么她下落得非常缓慢；\n@cue 因为在坠落的途中，她竟有充足的时间环顾四周，猜想接下来将会发生什么。[-]她试着向下望去，却只能看见一片黑暗\n@cue 向下[-]，向下[-]，再向下\n@cue 这样的坠落难道永远不会结束吗？\n\n\n\n@choice \"吃下我！\" goto:#StoryBegin\n#StoryBegin\n@stopSfx group:noise fade:2\n@sfx sfx/glug-glug-glug group:glug volume:0.2\n@sfx sfx/gentle-rain-loop group:rain loop:true volume:0.1\n@showUI dialog time:2 wait!\nnar: 最烂的天气我会投雨天一票\nnar: 最烂的城市我大概率会把投票箱敲了全都塞给南方\nnar: 最烂的南方的雨季里遇上了最烂的雨天[>]\nnar: 最烂的一天就是在最烂的南方的雨季里遇上了最烂的雨天[>]\nnar: 最烂的雨天发生在最烂的南方的雨季里最烂的一天[>]\nnar: 最烂的南方的最烂的一天就是最烂的雨季里遇上了最烂的南方的雨季碰上了最烂的……[>]\n@choice \"喂！\" goto:#PartRain\n\n#PartRain\nnar: 哎呀，你来啦\nnar: 可是尽管，天气会很湿，闷的墙壁上仿佛要渗出血，雨帘在路上拉起一层又一层的帷幕\nnar: 可是尽管，路面会很滑，某个地砖会像真正的地雷那样把你从袜子到裤脚全都打湿\nnar: 可是即便如此，我还是\nnar: 我还是最、还是最、最……\n@bgm bgm/dead-fish-riffle group:music volume:0.35 fade:5\n@sfx group:rain volume:0.3 time:2\n@rain power:1 wind:-1 hue:1 tint:0.8 time:5\nnar: 最喜欢雨天了\nnar: 即便如此在南方这些比烂的天气里，即使这个天气如此的糟糕，但我还是最喜欢雨天\n@choice \"为什么？\" goto:#PartRain2\n\n#PartRain2\nnar: 很闷就意味着喘不过气，自然平等的将它的暴力行使在每个人的咽喉\nnar: 不再有那些聒噪的行人，每个人都行色匆匆，街上只会空空荡荡\nnar: 至于我……\nnar: 不觉得这是一种很独特的体验吗。更好笑的事情是，还需要一边胆战心惊，害怕自己的耳机被雨淋坏，一边在雨里面展开双臂，幻想自己就是风和雨的天命神选，在这无人的街道上展露自己的恣意\nnar: ……[>]\n@inback bg/home effect:fade time:0.5 wait!\nnar: 好吧，我承认，我承认这有时候会变成一种自我陶醉和扮演。但是比起扮演我更喜欢将这视作是一种逃跑。渺小的自己和广袤的世界，人类文明如此繁荣的今天依然无法抗衡的伟大存在\nnar: 如果神明真的存在的话，它大概就会是掌管风雨的形象吧。我只是想融化在这场雨里面，融化在这个世界中那样\nnar: 比起很多努力扮演松弛的活着的人，我只是很想在雨声中寻找一场可以把自己淹没的好梦\nnar: 妈妈在喊我了\n@charTone rain\n@char alice pos:50 time:0.3 wait!\nnar: 雨幕里，一个熟悉的人影停在了街角。\nAlice: 你真的在这里淋了这么久？\n@char alice.eye1,mouth3,armR4 pos:50 wait!\nAlice: 妈妈让我来找你。她说牛奶再不买，店就要关门了。\n@char alice.eye4,mouth4,armR2,armL5 pos:50 wait!\nAlice: 还有，伞往这边一点。你半边肩膀都湿透了。\n@char alice.eye2,mouth2,armR0,armL0 pos:50 wait!\nnar: 她把伞沿朝我这边压低了一点，像是不打算再给我逃跑的机会。\n\n@choice \"陪我去买牛奶吧\" goto:game-a/chapter-02.nani#Start\n",
      "scriptRevision": "sha256:9dbcce75263cc5b75501f3451012eac4b3dca678d5e2a59f78fd261e7ef15a5e"
    }
  } satisfies Record<string, VnRuntimeScriptSource>;

export const gameAScriptCatalog = [
    {
      "scriptPath": "game-a/chapter-02.nani",
      "sourceText": "#Start\n@charTone rain\n@char alice.eye1,mouth1,armR1,armL0 pos:50 wait!\nAlice: 这还差不多。跟紧一点，别又站在雨里发呆。\nnar: 她把伞抬高了一些，刚好让我们都能看见前面的路。\n@char alice.eye4,mouth4,armR0,armL5 pos:50 wait!\nAlice: 先说好，到了店里不许挑半天。妈妈只让我们买牛奶。\nnar: 我问她，既然只是买牛奶，为什么出门前还特意换了双不怕水的鞋。\n@char alice.eye3,mouth3,armR0,armL2 pos:50 wait!\nAlice: 因为我知道某个人一定会踩遍路上每一个水坑。\nAlice: 尤其是那种看起来很浅，实际上能把袜子整个灌满的。\n@char alice.eye0,mouth5,armR0,armL0 pos:50 wait!\nnar: 她说得像一位经验丰富的灾害预报员，却还是把伞更多地偏向了我这边。\nAlice: 你笑什么？我只是不想回去以后听你打喷嚏。\n@char alice.eye1,mouth2,armR4,armL0 pos:50 wait!\nAlice: 而且你要是真感冒了，最后被妈妈叫去端热水的人还是我。\nnar: 我点点头，郑重保证接下来一步也不会踩错。\n@char alice.eye4,mouth3,armR0,armL2 pos:50 wait!\nAlice: 停。你脚边那个就是。\nnar: 鞋尖在水坑边缘悬了一瞬。我收回脚，雨滴随即替我在水面踩出密密麻麻的波纹。\n@char alice.eye0,mouth1,armR1,armL0 pos:50 wait!\nAlice: 看吧。没有我，你走不到街口就会宣布全军覆没。\nnar: 她的语气得意得过分。我决定转移话题，问她准备买哪一种牛奶。\n@char alice.eye4,mouth4,armR0,armL5 pos:50 wait!\nAlice: 原味。购物清单上写得很清楚，原、味、牛、奶。\nnar: 我提醒她，冰柜最上层通常还会放草莓味和巧克力味。\n@char alice.eye1,mouth6,armR4,armL0 pos:50 wait!\nAlice: ……如果巧克力味刚好在打折，也不是不能顺便看一眼。\nnar: 雨声忽然变得轻快起来。也许只是因为她终于承认，这趟出门并不完全是为了完成任务。\n@char alice.eye4,mouth2,armR0,armL2 pos:50 wait!\nAlice: 但是只能看一眼。你不要露出那种已经准备搬空冰柜的表情。\nnar: 我说我脸上只有对生活最朴素的期待。\n@char alice.eye0,mouth3,armR2,armL0 pos:50 wait!\nAlice: 那就把你的期待收好，先过马路。\nnar: 她伸手挡在我身前，等一辆溅着水花的车驶过去，才带着我踏进斑马线。\n@char alice.eye0,mouth1,armR0,armL0 pos:50 wait!\nnar: 我们挤在同一把伞下向亮着灯的街角走去。雨还没有停，但这条路已经没有刚才那么漫长了。\n@stopSfx group:rain fade:0.8\n@stopBgm group:music fade:0.8\n@end\n",
      "scriptRevision": "sha256:3fa3677c80979db90ea34241c3ce106d3b86716228b8b56a8bfe21a5fbd9a1ad"
    },
    {
      "scriptPath": "game-a/opening.nani",
      "sourceText": "#Start\n@hideUI dialog\n@sfx sfx/noise-6hz group:noise volume:0.3 loop!\n\n@cue 转眼之间，爱丽丝也跟着跳了下去\n@cue 压根没有想过自己以后该怎样出来\n@cue 要么这口井实在太深，要么她下落得非常缓慢；\n@cue 因为在坠落的途中，她竟有充足的时间环顾四周，猜想接下来将会发生什么。[-]她试着向下望去，却只能看见一片黑暗\n@cue 向下[-]，向下[-]，再向下\n@cue 这样的坠落难道永远不会结束吗？\n\n\n\n@choice \"吃下我！\" goto:#StoryBegin\n#StoryBegin\n@stopSfx group:noise fade:2\n@sfx sfx/glug-glug-glug group:glug volume:0.2\n@sfx sfx/gentle-rain-loop group:rain loop:true volume:0.1\n@showUI dialog time:2 wait!\nnar: 最烂的天气我会投雨天一票\nnar: 最烂的城市我大概率会把投票箱敲了全都塞给南方\nnar: 最烂的南方的雨季里遇上了最烂的雨天[>]\nnar: 最烂的一天就是在最烂的南方的雨季里遇上了最烂的雨天[>]\nnar: 最烂的雨天发生在最烂的南方的雨季里最烂的一天[>]\nnar: 最烂的南方的最烂的一天就是最烂的雨季里遇上了最烂的南方的雨季碰上了最烂的……[>]\n@choice \"喂！\" goto:#PartRain\n\n#PartRain\nnar: 哎呀，你来啦\nnar: 可是尽管，天气会很湿，闷的墙壁上仿佛要渗出血，雨帘在路上拉起一层又一层的帷幕\nnar: 可是尽管，路面会很滑，某个地砖会像真正的地雷那样把你从袜子到裤脚全都打湿\nnar: 可是即便如此，我还是\nnar: 我还是最、还是最、最……\n@bgm bgm/dead-fish-riffle group:music volume:0.35 fade:5\n@sfx group:rain volume:0.3 time:2\n@rain power:1 wind:-1 hue:1 tint:0.8 time:5\nnar: 最喜欢雨天了\nnar: 即便如此在南方这些比烂的天气里，即使这个天气如此的糟糕，但我还是最喜欢雨天\n@choice \"为什么？\" goto:#PartRain2\n\n#PartRain2\nnar: 很闷就意味着喘不过气，自然平等的将它的暴力行使在每个人的咽喉\nnar: 不再有那些聒噪的行人，每个人都行色匆匆，街上只会空空荡荡\nnar: 至于我……\nnar: 不觉得这是一种很独特的体验吗。更好笑的事情是，还需要一边胆战心惊，害怕自己的耳机被雨淋坏，一边在雨里面展开双臂，幻想自己就是风和雨的天命神选，在这无人的街道上展露自己的恣意\nnar: ……[>]\n@inback bg/home effect:fade time:0.5 wait!\nnar: 好吧，我承认，我承认这有时候会变成一种自我陶醉和扮演。但是比起扮演我更喜欢将这视作是一种逃跑。渺小的自己和广袤的世界，人类文明如此繁荣的今天依然无法抗衡的伟大存在\nnar: 如果神明真的存在的话，它大概就会是掌管风雨的形象吧。我只是想融化在这场雨里面，融化在这个世界中那样\nnar: 比起很多努力扮演松弛的活着的人，我只是很想在雨声中寻找一场可以把自己淹没的好梦\nnar: 妈妈在喊我了\n@charTone rain\n@char alice pos:50 time:0.3 wait!\nnar: 雨幕里，一个熟悉的人影停在了街角。\nAlice: 你真的在这里淋了这么久？\n@char alice.eye1,mouth3,armR4 pos:50 wait!\nAlice: 妈妈让我来找你。她说牛奶再不买，店就要关门了。\n@char alice.eye4,mouth4,armR2,armL5 pos:50 wait!\nAlice: 还有，伞往这边一点。你半边肩膀都湿透了。\n@char alice.eye2,mouth2,armR0,armL0 pos:50 wait!\nnar: 她把伞沿朝我这边压低了一点，像是不打算再给我逃跑的机会。\n\n@choice \"陪我去买牛奶吧\" goto:game-a/chapter-02.nani#Start\n",
      "scriptRevision": "sha256:9dbcce75263cc5b75501f3451012eac4b3dca678d5e2a59f78fd261e7ef15a5e"
    }
  ] as const satisfies VnRuntimeScriptCatalog;

export const gameAVoiceIndex = {
    "zh": {}
  } as const;

export const gameANaniProductionSemanticRevisions = {
    "game-a/chapter-02.nani": "sha256:3fa3677c80979db90ea34241c3ce106d3b86716228b8b56a8bfe21a5fbd9a1ad",
    "game-a/opening.nani": "sha256:9dbcce75263cc5b75501f3451012eac4b3dca678d5e2a59f78fd261e7ef15a5e"
  } as const;

export const gameANaniProductionDiagnostics = [] as const;
