import type { AssetRef } from "@v-ronpa/contracts";
import type { LayeredCharacterPreloadPlan } from "@v-ronpa/app-vn-shell";

// Generated by scripts/generate-assets.mjs. Do not edit by hand.
export const gameATestScriptMetadataByPath = {
    "game-a/test/smoke.nani": {
      "scriptRevision": "sha256:fc48b681ce6a6043822e67ff348d11817b35558d2cd393fd0c93451a0afc021e",
      "assetRefs": [
        {
          "id": "alice",
          "kind": "character-pack",
          "tags": []
        },
        {
          "id": "bg:game-a-academy-hall-fullscreen",
          "kind": "background",
          "tags": []
        },
        {
          "id": "bg:game-a-snow-outskirts-frame",
          "kind": "background",
          "tags": []
        },
        {
          "id": "bgm:game-a-main",
          "kind": "bgm",
          "tags": []
        },
        {
          "id": "sfx:gentle-rain-loop",
          "kind": "sfx",
          "tags": []
        },
        {
          "id": "voice:zh:game_a_voice_0001",
          "kind": "voice",
          "tags": []
        }
      ],
      "characterPreloadPlan": [
        {
          "characterId": "alice",
          "appearanceExpressions": [
            ""
          ]
        }
      ]
    },
    "game-a/test/character-smoke.nani": {
      "scriptRevision": "sha256:566b52066e57a8e08c85c6dea367149308e8504f23fa747c8ad1ff67cf3cce45",
      "assetRefs": [
        {
          "id": "alice",
          "kind": "character-pack",
          "tags": []
        },
        {
          "id": "bg:game-a-academy-hall-fullscreen",
          "kind": "background",
          "tags": []
        }
      ],
      "characterPreloadPlan": [
        {
          "characterId": "alice",
          "appearanceExpressions": [
            "",
            "EYE0,MOUTH0",
            "EYE1,MOUTH3,ArmL2",
            "EYE2,MOUTH2,ArmL0,ArmR0,EFFECT2",
            "EYE4,MOUTH5,ArmL4,ArmR2,EFFECT0"
          ]
        }
      ]
    }
  } satisfies Record<string, { scriptRevision: string; assetRefs: AssetRef[]; characterPreloadPlan: LayeredCharacterPreloadPlan }>;
