import type { AssetDefinition, AssetId } from "@v-ronpa/contracts";

// Generated by scripts/generate-assets.mjs. Do not edit by hand.
export const gameAAssets = [
    {
      "id": "bg/academy-hall",
      "uri": "assets/bg/academy-hall.png",
      "mimeType": "image/png"
    },
    {
      "id": "bg/home",
      "uri": "assets/bg/home.png",
      "mimeType": "image/png"
    },
    {
      "id": "bg/home-kitchen",
      "uri": "assets/bg/home-kitchen.png",
      "mimeType": "image/png"
    },
    {
      "id": "bg/inner/snow-outskirts",
      "uri": "assets/bg/inner/snow-outskirts.png",
      "mimeType": "image/png"
    },
    {
      "id": "bg/milk-scatter",
      "uri": "assets/bg/milk-scatter.png",
      "mimeType": "image/png"
    },
    {
      "id": "bg/milk-scatter-boom",
      "uri": "assets/bg/milk-scatter-boom.png",
      "mimeType": "image/png"
    },
    {
      "id": "bg/title",
      "uri": "assets/bg/title.png",
      "mimeType": "image/png"
    },
    {
      "id": "bgm/dark-ambient-home",
      "uri": "assets/bgm/dark-ambient-home.ogg",
      "mimeType": "audio/ogg"
    },
    {
      "id": "bgm/dead-fish-riffle",
      "uri": "assets/bgm/dead-fish-riffle.mp3",
      "mimeType": "audio/mpeg"
    },
    {
      "id": "bgm/industrial-rock-beat-tense",
      "uri": "assets/bgm/industrial-rock-beat-tense.ogg",
      "mimeType": "audio/ogg"
    },
    {
      "id": "bgm/main",
      "uri": "assets/bgm/main.ogg",
      "mimeType": "audio/ogg"
    },
    {
      "id": "bleep/dialogue",
      "uri": "assets/bleep/dialogue.ogg",
      "mimeType": "audio/ogg"
    },
    {
      "id": "char/alice",
      "uri": "assets/char/alice/character.json",
      "mimeType": "application/json"
    },
    {
      "id": "char/alice-kid",
      "uri": "assets/char/alice-kid/character.json",
      "mimeType": "application/json"
    },
    {
      "id": "font/fusion-pixel-zh-hans",
      "uri": "assets/font/fusion-pixel-zh-hans.woff2",
      "mimeType": "font/woff2"
    },
    {
      "id": "sfx/gentle-rain-loop",
      "uri": "assets/sfx/gentle-rain-loop.mp3",
      "mimeType": "audio/mpeg"
    },
    {
      "id": "sfx/glug-glug-glug",
      "uri": "assets/sfx/glug-glug-glug.mp3",
      "mimeType": "audio/mpeg"
    },
    {
      "id": "sfx/noise-6hz",
      "uri": "assets/sfx/noise-6hz.mp3",
      "mimeType": "audio/mpeg"
    },
    {
      "id": "sfx/pixabay-fall-impact",
      "uri": "assets/sfx/pixabay-fall-impact.mp3",
      "mimeType": "audio/mpeg"
    },
    {
      "id": "sfx/pixabay-wet-splat",
      "uri": "assets/sfx/pixabay-wet-splat.mp3",
      "mimeType": "audio/mpeg"
    },
    {
      "id": "sfx/ui-click-default",
      "uri": "assets/sfx/ui-click-default.ogg",
      "mimeType": "audio/ogg"
    },
    {
      "id": "sfx/ui-hover-default",
      "uri": "assets/sfx/ui-hover-default.ogg",
      "mimeType": "audio/ogg"
    },
    {
      "id": "ui/dialog-frame",
      "uri": "assets/ui/dialog-frame.png",
      "mimeType": "image/png"
    },
    {
      "id": "video/intro",
      "uri": "assets/video/intro.mp4",
      "mimeType": "video/mp4"
    },
    {
      "id": "voice/zh/voice-0001",
      "uri": "assets/voice/zh/voice-0001.ogg",
      "mimeType": "audio/ogg"
    }
  ] satisfies AssetDefinition[];

export const gameACharacterAssetIdByCharacterId = {
    "alice": "char/alice",
    "alice-kid": "char/alice-kid"
  } satisfies Record<string, AssetId>;
