import type { AssetRef, VnRuntimeScriptSource } from "@v-ronpa/contracts";
import type { LayeredCharacterPreloadPlan } from "@v-ronpa/app-vn-shell";

// Generated by scripts/generate-assets.mjs. Do not edit by hand.
export const gameATestScriptMetadataByPath = {
    "game-a/test/smoke.nani": {
      "scriptRevision": "sha256:c0673449a776f61399c429ffa7c9152ea4ae708537bfe89338565b0c3c8cfaa0",
      "assetRefs": [
        {
          "id": "alice",
          "kind": "character-pack",
          "tags": []
        },
        {
          "id": "bg:game-a-academy-hall-fullscreen",
          "kind": "background",
          "tags": []
        },
        {
          "id": "bg:game-a-snow-outskirts-frame",
          "kind": "background",
          "tags": []
        },
        {
          "id": "bgm:game-a-main",
          "kind": "bgm",
          "tags": []
        },
        {
          "id": "sfx:gentle-rain-loop",
          "kind": "sfx",
          "tags": []
        },
        {
          "id": "voice:zh:game_a_voice_0001",
          "kind": "voice",
          "tags": []
        },
        {
          "id": "voice:zh:smoke_preview_00",
          "kind": "voice",
          "tags": []
        }
      ],
      "characterPreloadPlan": [
        {
          "characterId": "alice",
          "appearanceExpressions": [
            ""
          ]
        }
      ]
    },
    "game-a/test/character-smoke.nani": {
      "scriptRevision": "sha256:566b52066e57a8e08c85c6dea367149308e8504f23fa747c8ad1ff67cf3cce45",
      "assetRefs": [
        {
          "id": "alice",
          "kind": "character-pack",
          "tags": []
        },
        {
          "id": "bg:game-a-academy-hall-fullscreen",
          "kind": "background",
          "tags": []
        }
      ],
      "characterPreloadPlan": [
        {
          "characterId": "alice",
          "appearanceExpressions": [
            "",
            "EYE0,MOUTH0",
            "EYE1,MOUTH3,ArmL2",
            "EYE2,MOUTH2,ArmL0,ArmR0,EFFECT2",
            "EYE4,MOUTH5,ArmL4,ArmR2,EFFECT0"
          ]
        }
      ]
    }
  } satisfies Record<string, { scriptRevision: string; assetRefs: AssetRef[]; characterPreloadPlan: LayeredCharacterPreloadPlan }>;

export const gameATestScriptSourcesByPath = {
    "game-a/test/smoke.nani": {
      "scriptPath": "game-a/test/smoke.nani",
      "sourceText": "#Start\n@showUI dialog\n@showUI commandBar visible:true\n@set route:\"smoke-preview\"\n@back bg:game-a-academy-hall-fullscreen effect:fade time:0.05\n@char alice pos:50\n@rain power:0.5 wind:-1 hue:215 tint:0.55\n@bgm bgm:game-a-main group:music volume:0.35\n@sfx sfx:gentle-rain-loop group:rain loop:true volume:0.2\nNarrator: CHECKPOINT SMOKE 00 - test-only VN entry is active.|#smoke_preview_00|\n@choice \"交互与存档\" goto:#Interaction\n@choice \"Pixi 与媒体\" goto:#Presentation\n\n#Interaction\n@set route:\"smoke-interaction\"\n@rain power:0\n@hideChars\n@hideUI dialog time:0.05 wait!\n@hideUI commandBar time:0.05 wait!\n@showUI dialog time:0.05 wait!\n@showUI commandBar visible:true time:0.05 wait!\nNarrator: CHECKPOINT SMOKE UI - terminal visibility is stable and saveable.\n@input playerName type:string summary:\"输入测试代号\" value:Felix\nNarrator: CHECKPOINT SMOKE INPUT - input wait completed.\n@wait i\nNarrator: CHECKPOINT SMOKE PAUSE - explicit runtime wait completed.\nNarrator: CHECKPOINT SMOKE SAVE LOAD SETTINGS - use shared command bar and pause sections now.\n@choice \"进入 Pixi 与媒体\" goto:#Presentation\n\n#Presentation\n@set route:\"smoke-presentation\"\n@back bg:game-a-academy-hall-fullscreen effect:fade time:0.05\n@inback bg:game-a-snow-outskirts-frame effect:fade time:0.05\n@char alice pos:50 time:0.05 wait!\n@rain power:0.5 wind:-1 hue:215 tint:0.55 time:0.05\n@flash color:#ffffff duration:50 wait!\nNarrator: CHECKPOINT SMOKE PIXI - renderer task completed without phantom waits.\n@choice \"继续媒体测试\" goto:#Media\n\n#Media\nMira: CHECKPOINT SMOKE VOICE - textId audio is optional runtime intent. |#game_a_voice_0001|\n@movie video:game-a-intro block:true\nNarrator: CHECKPOINT SMOKE MOVIE - media wait completed and is not saveable playback state.\n@rain power:0 time:0.05 wait!\n@hideChars time:0.05 wait!\nNarrator: CHECKPOINT SMOKE COMPLETE\n@end\n",
      "scriptRevision": "sha256:c0673449a776f61399c429ffa7c9152ea4ae708537bfe89338565b0c3c8cfaa0"
    },
    "game-a/test/character-smoke.nani": {
      "scriptPath": "game-a/test/character-smoke.nani",
      "sourceText": "#Start\n@showUI dialog\n@showUI commandBar visible:true\n@back bg:game-a-academy-hall-fullscreen effect:fade time:0.05\n@char alice pos:50 scale:0.78,0.78,1 time:0.3 wait!\nNarrator: CHECKPOINT CHARACTER 00 - default composition.\n@char alice.EYE0,MOUTH0 pos:50 wait!\nNarrator: CHECKPOINT CHARACTER 01 - eye and mouth replacement.\n@char alice.EYE1,MOUTH3,ArmL2 pos:50 wait!\nNarrator: CHECKPOINT CHARACTER 02 - left arm replacement.\n@char alice.EYE4,MOUTH5,ArmL4,ArmR2,EFFECT0 pos:50 wait!\nNarrator: CHECKPOINT CHARACTER 03 - both arms and effect replacement.\n@char alice.EYE2,MOUTH2,ArmL0,ArmR0,EFFECT2 pos:50 wait!\nNarrator: CHECKPOINT CHARACTER 04 - final multilayer composition.\n@choice \"完成角色测试\" goto:#Complete\n\n#Complete\nNarrator: CHECKPOINT CHARACTER COMPLETE\n@end\n",
      "scriptRevision": "sha256:566b52066e57a8e08c85c6dea367149308e8504f23fa747c8ad1ff67cf3cce45"
    }
  } satisfies Record<string, VnRuntimeScriptSource>;
