import type { AssetRef, FontFaceDefinition, RuntimeAsset } from "@v-ronpa/contracts";
import type { RuntimeAssetFragment } from "@v-ronpa/asset-registry";
import { pixiRuntimeAssetFragment } from "@v-ronpa/runtime-assets-pixi";

// Generated by scripts/generate-assets.mjs. Do not edit by hand.
export const gameARuntimeAssets = [
    {
      "id": "alice",
      "kind": "character-pack",
      "optimizedUri": "/game-a/characters/alice/character.json",
      "format": "json",
      "compression": [],
      "lods": [],
      "collisionProxyIds": [],
      "tags": [
        "game-a",
        "vn"
      ]
    },
    {
      "id": "bg:eat-pill",
      "kind": "background",
      "optimizedUri": "/game-a/backgrounds/eat-pill.png",
      "format": "png",
      "compression": [],
      "lods": [],
      "collisionProxyIds": [],
      "tags": [
        "game-a",
        "vn"
      ]
    },
    {
      "id": "bg:game-a-academy-hall-fullscreen",
      "kind": "background",
      "optimizedUri": "/game-a/backgrounds/game-a-academy-hall-fullscreen.png",
      "format": "png",
      "compression": [],
      "lods": [],
      "collisionProxyIds": [],
      "tags": [
        "game-a",
        "vn"
      ]
    },
    {
      "id": "bg:game-a-snow-outskirts-frame",
      "kind": "background",
      "optimizedUri": "/game-a/backgrounds/game-a-snow-outskirts-frame.png",
      "format": "png",
      "compression": [],
      "lods": [],
      "collisionProxyIds": [],
      "tags": [
        "game-a",
        "vn"
      ]
    },
    {
      "id": "bg:home-outside",
      "kind": "background",
      "optimizedUri": "/game-a/backgrounds/home-outside.png",
      "format": "png",
      "compression": [],
      "lods": [],
      "collisionProxyIds": [],
      "tags": [
        "game-a",
        "vn"
      ]
    },
    {
      "id": "bgm:dead-fish-riffle",
      "kind": "bgm",
      "optimizedUri": "/game-a/media/bgm/dead-fish-riffle.mp3",
      "format": "mp3",
      "compression": [],
      "lods": [],
      "collisionProxyIds": [],
      "tags": [
        "game-a",
        "vn"
      ]
    },
    {
      "id": "bgm:game-a-main",
      "kind": "bgm",
      "optimizedUri": "/game-a/media/bgm/game-a-main.ogg",
      "format": "ogg",
      "compression": [],
      "lods": [],
      "collisionProxyIds": [],
      "tags": [
        "game-a",
        "vn"
      ]
    },
    {
      "id": "bleep:game-a-dialogue",
      "kind": "bleep",
      "optimizedUri": "/game-a/media/bleep/game-a-dialogue.ogg",
      "format": "ogg",
      "compression": [],
      "lods": [],
      "collisionProxyIds": [],
      "tags": [
        "game-a",
        "vn"
      ]
    },
    {
      "id": "font:fusion-pixel-12px-proportional-zh-hans",
      "kind": "font",
      "optimizedUri": "/game-a/fonts/fusion-pixel-12px-proportional-zh-hans.woff2",
      "format": "woff2",
      "compression": [],
      "lods": [],
      "collisionProxyIds": [],
      "tags": [
        "game-a",
        "vn"
      ]
    },
    {
      "id": "sfx:game-a-chime",
      "kind": "sfx",
      "optimizedUri": "/game-a/media/sfx/game-a-chime.ogg",
      "format": "ogg",
      "compression": [],
      "lods": [],
      "collisionProxyIds": [],
      "tags": [
        "game-a",
        "vn"
      ]
    },
    {
      "id": "sfx:gentle-rain-loop",
      "kind": "sfx",
      "optimizedUri": "/game-a/media/sfx/gentle-rain-loop.mp3",
      "format": "mp3",
      "compression": [],
      "lods": [],
      "collisionProxyIds": [],
      "tags": [
        "game-a",
        "vn"
      ]
    },
    {
      "id": "sfx:glug-glug-glug",
      "kind": "sfx",
      "optimizedUri": "/game-a/media/sfx/glug-glug-glug.mp3",
      "format": "mp3",
      "compression": [],
      "lods": [],
      "collisionProxyIds": [],
      "tags": [
        "game-a",
        "vn"
      ]
    },
    {
      "id": "sfx:noise-6hz",
      "kind": "sfx",
      "optimizedUri": "/game-a/media/sfx/noise-6hz.mp3",
      "format": "mp3",
      "compression": [],
      "lods": [],
      "collisionProxyIds": [],
      "tags": [
        "game-a",
        "vn"
      ]
    },
    {
      "id": "sfx:ui-click-default",
      "kind": "sfx",
      "optimizedUri": "/game-a/media/sfx/ui-click-default.ogg",
      "format": "ogg",
      "compression": [],
      "lods": [],
      "collisionProxyIds": [],
      "tags": [
        "game-a",
        "vn"
      ]
    },
    {
      "id": "sfx:ui-hover-default",
      "kind": "sfx",
      "optimizedUri": "/game-a/media/sfx/ui-hover-default.ogg",
      "format": "ogg",
      "compression": [],
      "lods": [],
      "collisionProxyIds": [],
      "tags": [
        "game-a",
        "vn"
      ]
    },
    {
      "id": "texture:ui:game-a-dialog-frame",
      "kind": "texture",
      "optimizedUri": "/game-a/ui/game-a-dialog-frame.png",
      "format": "png",
      "compression": [],
      "lods": [],
      "collisionProxyIds": [],
      "tags": [
        "game-a",
        "ui",
        "vn"
      ]
    },
    {
      "id": "video:game-a-intro",
      "kind": "video",
      "optimizedUri": "/game-a/media/video/game-a-intro.mp4",
      "format": "mp4",
      "compression": [],
      "lods": [],
      "collisionProxyIds": [],
      "tags": [
        "game-a",
        "vn"
      ]
    },
    {
      "id": "voice:zh:game_a_voice_0001",
      "kind": "voice",
      "optimizedUri": "/game-a/media/voice/zh/game_a_voice_0001.ogg",
      "format": "ogg",
      "compression": [],
      "lods": [],
      "collisionProxyIds": [],
      "tags": [
        "game-a",
        "vn"
      ]
    }
  ] satisfies RuntimeAsset[];

export const gameAFontFaces = [
    {
      "id": "font:fusion-pixel-zh-hans",
      "family": "Fusion Pixel 12px zh-Hans",
      "sourceRef": "font:fusion-pixel-12px-proportional-zh-hans",
      "weight": "400",
      "style": "normal"
    }
  ] satisfies FontFaceDefinition[];

export const gameARuntimeAssetFragments = [pixiRuntimeAssetFragment] satisfies RuntimeAssetFragment[];

export const gameAScriptMetadataByPath = {
    "game-a/opening.nani": {
      "scriptRevision": "sha256:1231a838a1153b52ac5b3e4bfbb73af7e6d8c8c7ff57ae9041b1d0fd15c4a5ee",
      "assetRefs": [
        {
          "id": "alice",
          "kind": "character-pack",
          "tags": []
        },
        {
          "id": "bg:home-outside",
          "kind": "background",
          "tags": []
        },
        {
          "id": "bgm:dead-fish-riffle",
          "kind": "bgm",
          "tags": []
        },
        {
          "id": "sfx:gentle-rain-loop",
          "kind": "sfx",
          "tags": []
        },
        {
          "id": "sfx:glug-glug-glug",
          "kind": "sfx",
          "tags": []
        },
        {
          "id": "sfx:noise-6hz",
          "kind": "sfx",
          "tags": []
        }
      ]
    },
    "game-a/smoke.nani": {
      "scriptRevision": "sha256:7efdfb3d29acbf318d4a512efadf2eed29522bc6d4bc8acfb7ad084089357f22",
      "assetRefs": [
        {
          "id": "alice",
          "kind": "character-pack",
          "tags": []
        },
        {
          "id": "bg:game-a-academy-hall-fullscreen",
          "kind": "background",
          "tags": []
        },
        {
          "id": "bg:game-a-snow-outskirts-frame",
          "kind": "background",
          "tags": []
        },
        {
          "id": "bgm:game-a-main",
          "kind": "bgm",
          "tags": []
        },
        {
          "id": "sfx:gentle-rain-loop",
          "kind": "sfx",
          "tags": []
        },
        {
          "id": "voice:zh:game_a_voice_0001",
          "kind": "voice",
          "tags": []
        }
      ]
    }
  } satisfies Record<string, { scriptRevision: string; assetRefs: AssetRef[] }>;
