import { existsSync, readdirSync, readFileSync, statSync, writeFileSync } from "node:fs";
import { createHash } from "node:crypto";
import { dirname, extname, join, relative, sep } from "node:path";
import { fileURLToPath, pathToFileURL } from "node:url";
import gameAAssetConfigInput from "../apps/game-a/asset.config.mjs";
import harnessAssetConfigInput from "../apps/game-harness/asset.config.mjs";
import { parseScenario } from "../packages/nani-parser/src/index.ts";
import {
  compileRuntimeScript,
  serializeRuntimeScriptSemantics
} from "../packages/nani-runtime-compiler/src/index.ts";
import { deriveLayeredCharacterPreloadPlan } from "../packages/layered-character/src/index.ts";

const repoRoot = dirname(fileURLToPath(new URL("../package.json", import.meta.url)));
const providerModuleById = new Map([
  ["pixi", { module: "@v-ronpa/runtime-assets-pixi", exportName: "pixiRuntimeAssetFragment" }]
]);

const kindByDirectory = new Map([
  ["backgrounds", "background"],
  ["media/bleep", "bleep"],
  ["media/bgm", "bgm"],
  ["media/sfx", "sfx"],
  ["media/video", "video"],
  ["fonts", "font"],
  ["models", "glb"],
  ["thumbnails", "texture"],
  ["ui", "texture"]
]);

const formatByExtension = new Map([
  [".gltf", "gltf"],
  [".glb", "glb"],
  [".json", "json"],
  [".png", "png"],
  [".webp", "webp"],
  [".avif", "avif"],
  [".ktx2", "ktx2"],
  [".woff", "woff"],
  [".woff2", "woff2"],
  [".ttf", "ttf"],
  [".otf", "otf"],
  [".mp3", "mp3"],
  [".ogg", "ogg"],
  [".mp4", "mp4"],
  [".webm", "webm"]
]);

const harnessAssetConfig = normalizeAssetConfig(harnessAssetConfigInput);
const gameAAssetConfig = normalizeAssetConfig(gameAAssetConfigInput);

const fontFormatPreference = new Map([
  ["woff2", 4],
  ["woff", 3],
  ["otf", 2],
  ["ttf", 1]
]);

export function generateHarnessRuntimeAssetsModule() {
  return generateRuntimeAssetsModule(collectHarnessRuntimeAssets(), collectHarnessFontFaces(), harnessAssetConfig);
}

export function collectHarnessRuntimeAssets() {
  return collectRuntimeAssets(harnessAssetConfig);
}

export function collectHarnessFontFaces() {
  return collectFontFaces(collectHarnessRuntimeAssets(), harnessAssetConfig);
}

export function generateGameARuntimeAssetsModule() {
  return generateRuntimeAssetsModule(collectGameARuntimeAssets(), collectGameAFontFaces(), gameAAssetConfig);
}

export function generateGameATestScriptMetadataModule() {
  return generateScriptMetadataModule(
    gameAAssetConfig.testScripts,
    gameAAssetConfig.testScriptMetadataExportName
  );
}

export function collectGameARuntimeAssets() {
  return collectRuntimeAssets(gameAAssetConfig);
}

export function collectGameAFontFaces() {
  return collectFontFaces(collectGameARuntimeAssets(), gameAAssetConfig);
}

function generateRuntimeAssetsModule(assets, fontFaces, config) {
  const body = JSON.stringify(assets, null, 2).replace(/\n/g, "\n  ");
  const fontFacesBody = JSON.stringify(fontFaces, null, 2).replace(/\n/g, "\n  ");
  const scriptMetadata = collectScriptMetadata(config.scripts, config);
  const scriptMetadataBody = JSON.stringify(scriptMetadata, null, 2).replace(/\n/g, "\n  ");
  const providerImports = config.providers.map((id) => {
    const provider = providerModuleById.get(id);
    if (!provider) throw new Error(`Unknown runtime asset provider '${id}' in ${config.id}.`);
    return `import { ${provider.exportName} } from \"${provider.module}\";`;
  });
  const providerExports = config.providers.map((id) => providerModuleById.get(id).exportName).join(", ");
  return [
    "import type { AssetRef, FontFaceDefinition, RuntimeAsset } from \"@v-ronpa/contracts\";",
    "import type { RuntimeAssetFragment } from \"@v-ronpa/asset-registry\";",
    "import type { LayeredCharacterPreloadPlan } from \"@v-ronpa/app-vn-shell\";",
    ...providerImports,
    "",
    "// Generated by scripts/generate-assets.mjs. Do not edit by hand.",
    `export const ${config.exportName} = ${body} satisfies RuntimeAsset[];`,
    "",
    `export const ${config.fontFacesExportName} = ${fontFacesBody} satisfies FontFaceDefinition[];`,
    "",
    `export const ${config.fragmentsExportName} = [${providerExports}] satisfies RuntimeAssetFragment[];`,
    "",
    `export const ${config.scriptMetadataExportName} = ${scriptMetadataBody} satisfies Record<string, { scriptRevision: string; assetRefs: AssetRef[]; characterPreloadPlan: LayeredCharacterPreloadPlan }>;`,
    ""
  ].join("\n");
}

function generateScriptMetadataModule(entries, exportName) {
  const scriptMetadataBody = JSON.stringify(
    collectScriptMetadata(entries, gameAAssetConfig),
    null,
    2
  ).replace(/\n/g, "\n  ");
  return [
    "import type { AssetRef } from \"@v-ronpa/contracts\";",
    "import type { LayeredCharacterPreloadPlan } from \"@v-ronpa/app-vn-shell\";",
    "",
    "// Generated by scripts/generate-assets.mjs. Do not edit by hand.",
    `export const ${exportName} = ${scriptMetadataBody} satisfies Record<string, { scriptRevision: string; assetRefs: AssetRef[]; characterPreloadPlan: LayeredCharacterPreloadPlan }>;`,
    ""
  ].join("\n");
}

function collectRuntimeAssets(config) {
  if (!existsSync(config.publicRoot)) return [];
  const assets = walkFiles(config.publicRoot)
    .flatMap((absolutePath) => {
      const rel = toPosix(relative(config.publicRoot, absolutePath));
      const ext = extname(rel);
      const format = formatByExtension.get(ext);
      if (!format) return [];
      const kind = kindForRelativePath(rel);
      if (!kind) return [];
      const asset = {
        id: idForRelativePath(rel, kind, config),
        kind,
        optimizedUri: `${config.publicBaseUri}/${rel}`,
        format,
        compression: [],
        lods: [],
        collisionProxyIds: []
      };
      return [{ ...asset, tags: tagsForAsset(config, asset) }];
    })
    .sort((left, right) => left.id.localeCompare(right.id) || left.format.localeCompare(right.format));
  return selectPreferredGeneratedAssets(assets);
}

function kindForRelativePath(rel) {
  const parts = rel.split("/");
  if (parts[0] === "media" && parts[1] === "voice") return parts.length === 4 ? "voice" : undefined;
  if (/^characters\/[^/]+\/character\.json$/u.test(rel)) return "character-pack";
  const withoutFile = rel.split("/").slice(0, -1).join("/");
  return kindByDirectory.get(withoutFile);
}

function idForRelativePath(rel, kind, config) {
  const override = config.idOverrides[rel];
  if (override) return override;
  if (kind === "character-pack") return rel.split("/")[1];
  const name = rel.split("/").at(-1).replace(extname(rel), "");
  if (kind === "voice") {
    const locale = rel.split("/").at(2);
    return `voice:${locale}:${name}`;
  }
  if (kind === "background") return `bg:${name}`;
  if (kind === "bleep") return `bleep:${name}`;
  if (kind === "bgm") return `bgm:${name}`;
  if (kind === "sfx") return `sfx:${name}`;
  if (kind === "video") return `video:${name}`;
  if (kind === "glb") return `model:${name}`;
  if (kind === "font") return `font:${name}`;
  if (rel.startsWith("ui/")) return `texture:ui:${name}`;
  return `texture:${name}`;
}

function collectFontFaces(assets, config) {
  return assets
    .filter((asset) => asset.kind === "font")
    .map((asset) => {
      const override = config.fontFaceOverrides[asset.id] ?? {};
      return {
        id: override.id ?? asset.id,
        family: override.family ?? asset.id,
        sourceRef: asset.id,
        weight: override.weight ?? "400",
        style: override.style ?? "normal"
      };
    })
    .sort((left, right) => left.id.localeCompare(right.id));
}

function selectPreferredGeneratedAssets(assets) {
  const byId = new Map();
  for (const asset of assets) {
    const previous = byId.get(asset.id);
    if (!previous) {
      byId.set(asset.id, asset);
      continue;
    }
    if (previous.kind === "font" && asset.kind === "font") {
      byId.set(asset.id, preferredFontAsset(previous, asset));
      continue;
    }
    throw new Error(`Duplicate generated runtime asset id '${asset.id}' from ${previous.optimizedUri} and ${asset.optimizedUri}.`);
  }
  return [...byId.values()].sort((left, right) => left.id.localeCompare(right.id));
}

function preferredFontAsset(left, right) {
  const leftPreference = fontFormatPreference.get(left.format) ?? 0;
  const rightPreference = fontFormatPreference.get(right.format) ?? 0;
  return rightPreference > leftPreference ? right : left;
}

function walkFiles(root) {
  const output = [];
  for (const name of readdirSync(root)) {
    const absolutePath = join(root, name);
    const stat = statSync(absolutePath);
    if (stat.isDirectory()) output.push(...walkFiles(absolutePath));
    else output.push(absolutePath);
  }
  return output;
}

function toPosix(path) {
  return path.split(sep).join("/");
}

function normalizeAssetConfig(config) {
  return {
    ...config,
    publicRoot: join(repoRoot, config.publicRoot),
    outputPath: join(repoRoot, config.outputPath),
    ...(config.testScriptOutputPath
      ? { testScriptOutputPath: join(repoRoot, config.testScriptOutputPath) }
      : {}),
    idOverrides: config.idOverrides ?? {},
    fontFaceOverrides: config.fontFaceOverrides ?? {},
    providers: config.providers ?? [],
    scripts: config.scripts ?? [],
    testScripts: config.testScripts ?? []
  };
}

function tagsForAsset(config, asset) {
  if (asset.kind === "texture" && asset.id.startsWith("texture:ui:") && config.uiTextureTags) {
    return config.uiTextureTags;
  }
  return config.tags;
}

function collectScriptMetadata(entries, config) {
  return Object.fromEntries(
    entries.map((entry) => {
      const sourcePath = join(repoRoot, entry.sourceFile);
      let sourceText = readFileSync(sourcePath, "utf8");
      if (entry.sourceFormat === "typescript-template") {
        const match = sourceText.match(/`([\s\S]*)`;\s*$/u);
        if (!match?.[1]) throw new Error(`Could not read script template from ${entry.sourceFile}.`);
        sourceText = match[1];
      }
      const parsed = parseScenario({ sourceText, scriptPath: entry.scriptPath });
      const compiled = compileRuntimeScript(parsed);
      const errors = [...parsed.diagnostics, ...compiled.diagnostics].filter((diagnostic) => diagnostic.severity === "error");
      if (errors.length > 0) {
        throw new Error(`${entry.sourceFile} failed compilation: ${errors.map((diagnostic) => diagnostic.message).join("; ")}`);
      }
      return [entry.scriptPath, {
        scriptRevision: createScriptRevision(compiled.script),
        assetRefs: deriveScriptAssetRefs(compiled.script, config),
        characterPreloadPlan: deriveLayeredCharacterPreloadPlan(compiled.script)
      }];
    })
  );
}

function deriveScriptAssetRefs(script, config) {
  const refs = [...script.assets];
  for (const command of script.commands) {
    const textId = command.commandId === "print" && typeof command.params.textId === "string"
      ? command.params.textId
      : undefined;
    if (!textId) continue;
    for (const locale of config.voiceLocales ?? []) {
      refs.push({ id: `voice:${locale}:${textId}`, kind: "voice", tags: [] });
    }
  }
  return dedupeAssetRefs(refs);
}

export function createScriptRevision(script) {
  return `sha256:${createHash("sha256").update(serializeRuntimeScriptSemantics(script)).digest("hex")}`;
}

function dedupeAssetRefs(assetRefs) {
  const byId = new Map();
  for (const asset of assetRefs) {
    if (asset.id.startsWith("group:")) continue;
    const previous = byId.get(asset.id);
    if (previous && previous.kind !== asset.kind) {
      throw new Error(`Script asset '${asset.id}' is referenced as both '${previous.kind}' and '${asset.kind}'.`);
    }
    byId.set(asset.id, { id: asset.id, kind: asset.kind, tags: asset.tags ?? [] });
  }
  return [...byId.values()].sort((left, right) => left.id.localeCompare(right.id) || left.kind.localeCompare(right.kind));
}

function main() {
  const outputs = [
    { path: harnessAssetConfig.outputPath, content: generateHarnessRuntimeAssetsModule() },
    { path: gameAAssetConfig.outputPath, content: generateGameARuntimeAssetsModule() },
    {
      path: gameAAssetConfig.testScriptOutputPath,
      content: generateGameATestScriptMetadataModule()
    }
  ];
  if (process.argv.includes("--check")) {
    for (const output of outputs) {
      const current = existsSync(output.path) ? readFileSync(output.path, "utf8") : "";
      if (current !== output.content) {
        console.error(`${relative(repoRoot, output.path)} is out of date. Run pnpm generate:assets.`);
        process.exitCode = 1;
      }
    }
    return;
  }
  for (const output of outputs) writeFileSync(output.path, output.content);
}

if (process.argv[1] && import.meta.url === pathToFileURL(process.argv[1]).href) main();
