import { existsSync, readdirSync, readFileSync, statSync, writeFileSync } from "node:fs";
import { dirname, extname, join, relative, sep } from "node:path";
import { fileURLToPath, pathToFileURL } from "node:url";

const repoRoot = dirname(fileURLToPath(new URL("../package.json", import.meta.url)));
const harnessRoot = join(repoRoot, "apps/game-harness/public/harness");
const gameARoot = join(repoRoot, "apps/game-a/public/game-a");
const harnessOutputPath = join(repoRoot, "apps/game-harness/src/harness/generatedAssets.ts");
const gameAOutputPath = join(repoRoot, "apps/game-a/src/generatedAssets.ts");

const kindByDirectory = new Map([
  ["backgrounds", "background"],
  ["media/bleep", "bleep"],
  ["media/bgm", "bgm"],
  ["media/sfx", "sfx"],
  ["media/video", "video"],
  ["fonts", "font"],
  ["models", "glb"],
  ["thumbnails", "texture"],
  ["ui", "texture"]
]);

const formatByExtension = new Map([
  [".gltf", "gltf"],
  [".glb", "glb"],
  [".json", "json"],
  [".png", "png"],
  [".webp", "webp"],
  [".avif", "avif"],
  [".ktx2", "ktx2"],
  [".woff", "woff"],
  [".woff2", "woff2"],
  [".ttf", "ttf"],
  [".otf", "otf"],
  [".mp3", "mp3"],
  [".ogg", "ogg"],
  [".mp4", "mp4"],
  [".webm", "webm"]
]);

const harnessAssetConfig = {
  publicRoot: harnessRoot,
  publicBaseUri: "/harness",
  exportName: "harnessRuntimeAssets",
  fontFacesExportName: "harnessFontFaces",
  idOverrides: new Map([
    ["media/bgm/bgm-validation-main.ogg", "bgm:validation-main"],
    ["media/bgm/bgm-validation-alt.ogg", "bgm:validation-alt"],
    ["media/bgm/bgm-validation-layer.ogg", "bgm:validation-layer"],
    ["media/bgm/bgm-validation-extra.ogg", "bgm:validation-extra"],
    ["media/video/movie-validation-intro.mp4", "video:validation-intro"],
    ["thumbnails/evidence-keycard.png", "texture:evidence:keycard-thumbnail"],
    ["thumbnails/item-notebook.png", "texture:item:notebook-thumbnail"]
  ]),
  fontFaceOverrides: new Map([
    [
      "font:rich-serif",
      {
        id: "font:serif",
        family: "V Ronpa Rich Serif"
      }
    ]
  ]),
  tagsForAsset: () => ["harness"]
};

const gameAAssetConfig = {
  publicRoot: gameARoot,
  publicBaseUri: "/game-a",
  exportName: "gameARuntimeAssets",
  fontFacesExportName: "gameAFontFaces",
  idOverrides: new Map(),
  fontFaceOverrides: new Map(),
  tagsForAsset: (asset) => (asset.kind === "texture" && asset.id.startsWith("texture:ui:") ? ["game-a", "ui", "vn"] : ["game-a", "vn"])
};

const fontFormatPreference = new Map([
  ["woff2", 4],
  ["woff", 3],
  ["otf", 2],
  ["ttf", 1]
]);

export function generateHarnessRuntimeAssetsModule() {
  return generateRuntimeAssetsModule(collectHarnessRuntimeAssets(), collectHarnessFontFaces(), harnessAssetConfig);
}

export function collectHarnessRuntimeAssets() {
  return collectRuntimeAssets(harnessAssetConfig);
}

export function collectHarnessFontFaces() {
  return collectFontFaces(collectHarnessRuntimeAssets(), harnessAssetConfig);
}

export function generateGameARuntimeAssetsModule() {
  return generateRuntimeAssetsModule(collectGameARuntimeAssets(), collectGameAFontFaces(), gameAAssetConfig);
}

export function collectGameARuntimeAssets() {
  return collectRuntimeAssets(gameAAssetConfig);
}

export function collectGameAFontFaces() {
  return collectFontFaces(collectGameARuntimeAssets(), gameAAssetConfig);
}

function generateRuntimeAssetsModule(assets, fontFaces, config) {
  const body = JSON.stringify(assets, null, 2).replace(/\n/g, "\n  ");
  const fontFacesBody = JSON.stringify(fontFaces, null, 2).replace(/\n/g, "\n  ");
  return [
    "import type { FontFaceDefinition, RuntimeAsset } from \"@v-ronpa/contracts\";",
    "",
    "// Generated by scripts/generate-assets.mjs. Do not edit by hand.",
    `export const ${config.exportName} = ${body} satisfies RuntimeAsset[];`,
    "",
    `export const ${config.fontFacesExportName} = ${fontFacesBody} satisfies FontFaceDefinition[];`,
    ""
  ].join("\n");
}

function collectRuntimeAssets(config) {
  if (!existsSync(config.publicRoot)) return [];
  const assets = walkFiles(config.publicRoot)
    .flatMap((absolutePath) => {
      const rel = toPosix(relative(config.publicRoot, absolutePath));
      const ext = extname(rel);
      const format = formatByExtension.get(ext);
      if (!format) return [];
      const kind = kindForRelativePath(rel);
      if (!kind) return [];
      const asset = {
        id: idForRelativePath(rel, kind, config),
        kind,
        optimizedUri: `${config.publicBaseUri}/${rel}`,
        format,
        compression: [],
        lods: [],
        collisionProxyIds: []
      };
      return [{ ...asset, tags: config.tagsForAsset(asset) }];
    })
    .sort((left, right) => left.id.localeCompare(right.id) || left.format.localeCompare(right.format));
  return selectPreferredGeneratedAssets(assets);
}

function kindForRelativePath(rel) {
  const parts = rel.split("/");
  if (parts[0] === "media" && parts[1] === "voice") return parts.length === 4 ? "voice" : undefined;
  if (/^characters\/[^/]+\/character\.json$/u.test(rel)) return "character-pack";
  const withoutFile = rel.split("/").slice(0, -1).join("/");
  return kindByDirectory.get(withoutFile);
}

function idForRelativePath(rel, kind, config) {
  const override = config.idOverrides.get(rel);
  if (override) return override;
  if (kind === "character-pack") return rel.split("/")[1];
  const name = rel.split("/").at(-1).replace(extname(rel), "");
  if (kind === "voice") {
    const locale = rel.split("/").at(2);
    return `voice:${locale}:${name}`;
  }
  if (kind === "background") return `bg:${name}`;
  if (kind === "bleep") return `bleep:${name}`;
  if (kind === "bgm") return `bgm:${name}`;
  if (kind === "sfx") return `sfx:${name}`;
  if (kind === "video") return `video:${name}`;
  if (kind === "glb") return `model:${name}`;
  if (kind === "font") return `font:${name}`;
  if (rel.startsWith("ui/")) return `texture:ui:${name}`;
  return `texture:${name}`;
}

function collectFontFaces(assets, config) {
  return assets
    .filter((asset) => asset.kind === "font")
    .map((asset) => {
      const override = config.fontFaceOverrides.get(asset.id) ?? {};
      return {
        id: override.id ?? asset.id,
        family: override.family ?? asset.id,
        sourceRef: asset.id,
        weight: override.weight ?? "400",
        style: override.style ?? "normal"
      };
    })
    .sort((left, right) => left.id.localeCompare(right.id));
}

function selectPreferredGeneratedAssets(assets) {
  const byId = new Map();
  for (const asset of assets) {
    const previous = byId.get(asset.id);
    if (!previous) {
      byId.set(asset.id, asset);
      continue;
    }
    if (previous.kind === "font" && asset.kind === "font") {
      byId.set(asset.id, preferredFontAsset(previous, asset));
      continue;
    }
    throw new Error(`Duplicate generated runtime asset id '${asset.id}' from ${previous.optimizedUri} and ${asset.optimizedUri}.`);
  }
  return [...byId.values()].sort((left, right) => left.id.localeCompare(right.id));
}

function preferredFontAsset(left, right) {
  const leftPreference = fontFormatPreference.get(left.format) ?? 0;
  const rightPreference = fontFormatPreference.get(right.format) ?? 0;
  return rightPreference > leftPreference ? right : left;
}

function walkFiles(root) {
  const output = [];
  for (const name of readdirSync(root)) {
    const absolutePath = join(root, name);
    const stat = statSync(absolutePath);
    if (stat.isDirectory()) output.push(...walkFiles(absolutePath));
    else output.push(absolutePath);
  }
  return output;
}

function toPosix(path) {
  return path.split(sep).join("/");
}

function main() {
  const outputs = [
    { path: harnessOutputPath, content: generateHarnessRuntimeAssetsModule() },
    { path: gameAOutputPath, content: generateGameARuntimeAssetsModule() }
  ];
  if (process.argv.includes("--check")) {
    for (const output of outputs) {
      const current = existsSync(output.path) ? readFileSync(output.path, "utf8") : "";
      if (current !== output.content) {
        console.error(`${relative(repoRoot, output.path)} is out of date. Run pnpm generate:assets.`);
        process.exitCode = 1;
      }
    }
    return;
  }
  for (const output of outputs) writeFileSync(output.path, output.content);
}

if (process.argv[1] && import.meta.url === pathToFileURL(process.argv[1]).href) main();
