import { existsSync, readdirSync, readFileSync, statSync, writeFileSync } from "node:fs";
import { dirname, extname, join, relative, sep } from "node:path";
import { fileURLToPath, pathToFileURL } from "node:url";

const repoRoot = dirname(fileURLToPath(new URL("../package.json", import.meta.url)));
const harnessRoot = join(repoRoot, "apps/game/public/harness");
const outputPath = join(repoRoot, "apps/game/src/harness/generatedAssets.ts");

const kindByDirectory = new Map([
  ["backgrounds", "background"],
  ["media/bgm", "bgm"],
  ["media/sfx", "sfx"],
  ["media/video", "video"],
  ["models", "glb"],
  ["thumbnails", "texture"]
]);

const formatByExtension = new Map([
  [".gltf", "gltf"],
  [".glb", "glb"],
  [".json", "json"],
  [".png", "png"],
  [".webp", "webp"],
  [".avif", "avif"],
  [".ktx2", "ktx2"],
  [".mp3", "mp3"],
  [".ogg", "ogg"],
  [".mp4", "mp4"],
  [".webm", "webm"]
]);

const idOverrides = new Map([
  ["media/bgm/bgm-validation-main.ogg", "bgm:validation-main"],
  ["media/bgm/bgm-validation-alt.ogg", "bgm:validation-alt"],
  ["media/bgm/bgm-validation-layer.ogg", "bgm:validation-layer"],
  ["media/bgm/bgm-validation-extra.ogg", "bgm:validation-extra"],
  ["media/video/movie-validation-intro.mp4", "video:validation-intro"],
  ["thumbnails/evidence-keycard.png", "texture:evidence:keycard-thumbnail"],
  ["thumbnails/item-notebook.png", "texture:item:notebook-thumbnail"]
]);

export function generateHarnessRuntimeAssetsModule() {
  const assets = collectHarnessRuntimeAssets();
  const body = JSON.stringify(assets, null, 2).replace(/\n/g, "\n  ");
  return [
    "import type { RuntimeAsset } from \"@v-ronpa/contracts\";",
    "",
    "// Generated by scripts/generate-assets.mjs. Do not edit by hand.",
    `export const harnessRuntimeAssets = ${body} satisfies RuntimeAsset[];`,
    ""
  ].join("\n");
}

export function collectHarnessRuntimeAssets() {
  if (!existsSync(harnessRoot)) return [];
  return walkFiles(harnessRoot)
    .flatMap((absolutePath) => {
      const rel = toPosix(relative(harnessRoot, absolutePath));
      const ext = extname(rel);
      const format = formatByExtension.get(ext);
      if (!format) return [];
      const kind = kindForRelativePath(rel);
      if (!kind) return [];
      return [
        {
          id: idForRelativePath(rel, kind),
          kind,
          optimizedUri: `/harness/${rel}`,
          format,
          compression: [],
          lods: [],
          collisionProxyIds: [],
          tags: ["harness"]
        }
      ];
    })
    .sort((left, right) => left.id.localeCompare(right.id));
}

function kindForRelativePath(rel) {
  if (/^characters\/[^/]+\/character\.json$/u.test(rel)) return "character-pack";
  const withoutFile = rel.split("/").slice(0, -1).join("/");
  return kindByDirectory.get(withoutFile);
}

function idForRelativePath(rel, kind) {
  const override = idOverrides.get(rel);
  if (override) return override;
  if (kind === "character-pack") return rel.split("/")[1];
  const name = rel.split("/").at(-1).replace(extname(rel), "");
  if (kind === "background") return `bg:${name}`;
  if (kind === "bgm") return `bgm:${name}`;
  if (kind === "sfx") return `sfx:${name}`;
  if (kind === "video") return `video:${name}`;
  if (kind === "glb") return `model:${name}`;
  return `texture:${name}`;
}

function walkFiles(root) {
  const output = [];
  for (const name of readdirSync(root)) {
    const absolutePath = join(root, name);
    const stat = statSync(absolutePath);
    if (stat.isDirectory()) output.push(...walkFiles(absolutePath));
    else output.push(absolutePath);
  }
  return output;
}

function toPosix(path) {
  return path.split(sep).join("/");
}

function main() {
  const next = generateHarnessRuntimeAssetsModule();
  if (process.argv.includes("--check")) {
    const current = existsSync(outputPath) ? readFileSync(outputPath, "utf8") : "";
    if (current !== next) {
      console.error(`${relative(repoRoot, outputPath)} is out of date. Run pnpm generate:assets.`);
      process.exitCode = 1;
    }
    return;
  }
  writeFileSync(outputPath, next);
}

if (process.argv[1] && import.meta.url === pathToFileURL(process.argv[1]).href) main();
