import { createHash } from "node:crypto";
import { existsSync, readFileSync } from "node:fs";
import { basename, dirname, resolve } from "node:path";

export const DEFAULT_DEV_PORT = 5173;
export const WORKTREE_ENV_FILE = ".env.worktree";
export const APP_DEV_PORT_OFFSETS = Object.freeze({
  "game-harness": 0,
  "game-a": 1
});

export function parseEnvText(text) {
  const values = {};

  for (const rawLine of text.split(/\r?\n/)) {
    const line = rawLine.trim();
    if (!line || line.startsWith("#")) continue;

    const separatorIndex = line.indexOf("=");
    if (separatorIndex === -1) continue;

    const key = line.slice(0, separatorIndex).trim();
    const value = line.slice(separatorIndex + 1).trim();
    if (key) values[key] = value;
  }

  return values;
}

export function findUp(filename, startDir = process.cwd()) {
  let current = resolve(startDir);

  while (true) {
    const candidate = resolve(current, filename);
    if (existsSync(candidate)) return candidate;

    const parent = dirname(current);
    if (parent === current) return undefined;
    current = parent;
  }
}

export function loadWorktreeEnv(startDir = process.cwd()) {
  const envPath = findUp(WORKTREE_ENV_FILE, startDir);
  if (!envPath) return { envPath: undefined, values: {} };

  return {
    envPath,
    values: parseEnvText(readFileSync(envPath, "utf8"))
  };
}

export function parsePort(value, fallback = DEFAULT_DEV_PORT) {
  const port = Number(value);
  if (Number.isInteger(port) && port >= 1024 && port <= 65535) return port;
  return fallback;
}

export function deriveWorktreePort(cwd = process.cwd()) {
  const hash = createHash("sha1").update(resolve(cwd)).digest("hex");
  const offset = Number.parseInt(hash.slice(0, 4), 16) % 1000;
  return DEFAULT_DEV_PORT + offset;
}

export function resolveWorktreeRuntimeEnv(startDir = process.cwd()) {
  const loaded = loadWorktreeEnv(startDir);
  const rawPort =
    process.env.VITE_DEV_PORT ??
    process.env.PORT ??
    loaded.values.VITE_DEV_PORT ??
    loaded.values.PORT;
  const port = parsePort(rawPort);

  return {
    envPath: loaded.envPath,
    values: loaded.values,
    port
  };
}

export function resolveWorktreeAppRuntimeEnv(appId, startDir = process.cwd()) {
  const runtime = resolveWorktreeRuntimeEnv(startDir);
  const offset = APP_DEV_PORT_OFFSETS[appId];
  if (offset === undefined) throw new Error(`Unknown worktree app id '${appId}'.`);
  return { ...runtime, appId, appOffset: offset, port: runtime.port + offset };
}

export function createWorktreeEnvContent({ cwd = process.cwd(), port = deriveWorktreePort(cwd) } = {}) {
  const resolvedCwd = resolve(cwd);
  const stateDir = ".local-state";

  return [
    `# Generated by scripts/setup-worktree-env.mjs`,
    `WORKTREE_NAME=${basename(resolvedCwd)}`,
    `PORT=${port}`,
    `VITE_DEV_PORT=${port}`,
    `LOCAL_STORAGE_DIR=${stateDir}/${basename(resolvedCwd)}`,
    ""
  ].join("\n");
}
