import type { RuntimeAsset } from "@v-ronpa/contracts";

// Generated by scripts/generate-assets.mjs. Do not edit by hand.
export const harnessRuntimeAssets = [
    {
      "id": "bg:black",
      "kind": "background",
      "optimizedUri": "/harness/backgrounds/black.png",
      "format": "png",
      "compression": [],
      "lods": [],
      "collisionProxyIds": [],
      "tags": [
        "harness"
      ]
    },
    {
      "id": "bg:classroom",
      "kind": "background",
      "optimizedUri": "/harness/backgrounds/classroom.png",
      "format": "png",
      "compression": [],
      "lods": [],
      "collisionProxyIds": [],
      "tags": [
        "harness"
      ]
    },
    {
      "id": "bg:harness",
      "kind": "background",
      "optimizedUri": "/harness/backgrounds/harness.png",
      "format": "png",
      "compression": [],
      "lods": [],
      "collisionProxyIds": [],
      "tags": [
        "harness"
      ]
    },
    {
      "id": "bgm:validation-alt",
      "kind": "bgm",
      "optimizedUri": "/harness/media/bgm/bgm-validation-alt.ogg",
      "format": "ogg",
      "compression": [],
      "lods": [],
      "collisionProxyIds": [],
      "tags": [
        "harness"
      ]
    },
    {
      "id": "bgm:validation-extra",
      "kind": "bgm",
      "optimizedUri": "/harness/media/bgm/bgm-validation-extra.ogg",
      "format": "ogg",
      "compression": [],
      "lods": [],
      "collisionProxyIds": [],
      "tags": [
        "harness"
      ]
    },
    {
      "id": "bgm:validation-layer",
      "kind": "bgm",
      "optimizedUri": "/harness/media/bgm/bgm-validation-layer.ogg",
      "format": "ogg",
      "compression": [],
      "lods": [],
      "collisionProxyIds": [],
      "tags": [
        "harness"
      ]
    },
    {
      "id": "bgm:validation-main",
      "kind": "bgm",
      "optimizedUri": "/harness/media/bgm/bgm-validation-main.ogg",
      "format": "ogg",
      "compression": [],
      "lods": [],
      "collisionProxyIds": [],
      "tags": [
        "harness"
      ]
    },
    {
      "id": "Ema",
      "kind": "character-pack",
      "optimizedUri": "/harness/characters/Ema/character.json",
      "format": "json",
      "compression": [],
      "lods": [],
      "collisionProxyIds": [],
      "tags": [
        "harness"
      ]
    },
    {
      "id": "model:academy-hall",
      "kind": "glb",
      "optimizedUri": "/harness/models/academy-hall.gltf",
      "format": "gltf",
      "compression": [],
      "lods": [],
      "collisionProxyIds": [],
      "tags": [
        "harness"
      ]
    },
    {
      "id": "model:classroom",
      "kind": "glb",
      "optimizedUri": "/harness/models/classroom.gltf",
      "format": "gltf",
      "compression": [],
      "lods": [],
      "collisionProxyIds": [],
      "tags": [
        "harness"
      ]
    },
    {
      "id": "model:props-case-file",
      "kind": "glb",
      "optimizedUri": "/harness/models/props-case-file.gltf",
      "format": "gltf",
      "compression": [],
      "lods": [],
      "collisionProxyIds": [],
      "tags": [
        "harness"
      ]
    },
    {
      "id": "model:props-door",
      "kind": "glb",
      "optimizedUri": "/harness/models/props-door.gltf",
      "format": "gltf",
      "compression": [],
      "lods": [],
      "collisionProxyIds": [],
      "tags": [
        "harness"
      ]
    },
    {
      "id": "sfx:knock-door",
      "kind": "sfx",
      "optimizedUri": "/harness/media/sfx/knock-door.ogg",
      "format": "ogg",
      "compression": [],
      "lods": [],
      "collisionProxyIds": [],
      "tags": [
        "harness"
      ]
    },
    {
      "id": "sfx:rain-inside-car-loop",
      "kind": "sfx",
      "optimizedUri": "/harness/media/sfx/rain-inside-car-loop.ogg",
      "format": "ogg",
      "compression": [],
      "lods": [],
      "collisionProxyIds": [],
      "tags": [
        "harness"
      ]
    },
    {
      "id": "sfx:shock-fadeout",
      "kind": "sfx",
      "optimizedUri": "/harness/media/sfx/shock-fadeout.ogg",
      "format": "ogg",
      "compression": [],
      "lods": [],
      "collisionProxyIds": [],
      "tags": [
        "harness"
      ]
    },
    {
      "id": "texture:evidence:keycard-thumbnail",
      "kind": "texture",
      "optimizedUri": "/harness/thumbnails/evidence-keycard.png",
      "format": "png",
      "compression": [],
      "lods": [],
      "collisionProxyIds": [],
      "tags": [
        "harness"
      ]
    },
    {
      "id": "texture:item:notebook-thumbnail",
      "kind": "texture",
      "optimizedUri": "/harness/thumbnails/item-notebook.png",
      "format": "png",
      "compression": [],
      "lods": [],
      "collisionProxyIds": [],
      "tags": [
        "harness"
      ]
    },
    {
      "id": "video:validation-intro",
      "kind": "video",
      "optimizedUri": "/harness/media/video/movie-validation-intro.mp4",
      "format": "mp4",
      "compression": [],
      "lods": [],
      "collisionProxyIds": [],
      "tags": [
        "harness"
      ]
    },
    {
      "id": "voice:zh:0102Adv03_Ema001",
      "kind": "voice",
      "optimizedUri": "/harness/media/voice/zh/0102Adv03_Ema001.ogg",
      "format": "ogg",
      "compression": [],
      "lods": [],
      "collisionProxyIds": [],
      "tags": [
        "harness"
      ]
    },
    {
      "id": "voice:zh:0102Adv03_Ema002",
      "kind": "voice",
      "optimizedUri": "/harness/media/voice/zh/0102Adv03_Ema002.ogg",
      "format": "ogg",
      "compression": [],
      "lods": [],
      "collisionProxyIds": [],
      "tags": [
        "harness"
      ]
    },
    {
      "id": "voice:zh:0102Adv03_Ema003",
      "kind": "voice",
      "optimizedUri": "/harness/media/voice/zh/0102Adv03_Ema003.ogg",
      "format": "ogg",
      "compression": [],
      "lods": [],
      "collisionProxyIds": [],
      "tags": [
        "harness"
      ]
    },
    {
      "id": "voice:zh:0102Adv03_Ema004",
      "kind": "voice",
      "optimizedUri": "/harness/media/voice/zh/0102Adv03_Ema004.ogg",
      "format": "ogg",
      "compression": [],
      "lods": [],
      "collisionProxyIds": [],
      "tags": [
        "harness"
      ]
    },
    {
      "id": "voice:zh:0102Adv03_Margo001",
      "kind": "voice",
      "optimizedUri": "/harness/media/voice/zh/0102Adv03_Margo001.ogg",
      "format": "ogg",
      "compression": [],
      "lods": [],
      "collisionProxyIds": [],
      "tags": [
        "harness"
      ]
    },
    {
      "id": "voice:zh:0102Adv03_Margo002",
      "kind": "voice",
      "optimizedUri": "/harness/media/voice/zh/0102Adv03_Margo002.ogg",
      "format": "ogg",
      "compression": [],
      "lods": [],
      "collisionProxyIds": [],
      "tags": [
        "harness"
      ]
    },
    {
      "id": "voice:zh:0102Adv03_Margo003",
      "kind": "voice",
      "optimizedUri": "/harness/media/voice/zh/0102Adv03_Margo003.ogg",
      "format": "ogg",
      "compression": [],
      "lods": [],
      "collisionProxyIds": [],
      "tags": [
        "harness"
      ]
    },
    {
      "id": "voice:zh:0102Adv03_Margo004",
      "kind": "voice",
      "optimizedUri": "/harness/media/voice/zh/0102Adv03_Margo004.ogg",
      "format": "ogg",
      "compression": [],
      "lods": [],
      "collisionProxyIds": [],
      "tags": [
        "harness"
      ]
    },
    {
      "id": "voice:zh:0102Adv03_Sherry001",
      "kind": "voice",
      "optimizedUri": "/harness/media/voice/zh/0102Adv03_Sherry001.ogg",
      "format": "ogg",
      "compression": [],
      "lods": [],
      "collisionProxyIds": [],
      "tags": [
        "harness"
      ]
    },
    {
      "id": "voice:zh:0102Adv03_Sherry002",
      "kind": "voice",
      "optimizedUri": "/harness/media/voice/zh/0102Adv03_Sherry002.ogg",
      "format": "ogg",
      "compression": [],
      "lods": [],
      "collisionProxyIds": [],
      "tags": [
        "harness"
      ]
    },
    {
      "id": "voice:zh:0102Adv03_Sherry003",
      "kind": "voice",
      "optimizedUri": "/harness/media/voice/zh/0102Adv03_Sherry003.ogg",
      "format": "ogg",
      "compression": [],
      "lods": [],
      "collisionProxyIds": [],
      "tags": [
        "harness"
      ]
    },
    {
      "id": "voice:zh:0102Adv03_Sherry004",
      "kind": "voice",
      "optimizedUri": "/harness/media/voice/zh/0102Adv03_Sherry004.ogg",
      "format": "ogg",
      "compression": [],
      "lods": [],
      "collisionProxyIds": [],
      "tags": [
        "harness"
      ]
    },
    {
      "id": "voice:zh:0102Adv04_Ema001",
      "kind": "voice",
      "optimizedUri": "/harness/media/voice/zh/0102Adv04_Ema001.ogg",
      "format": "ogg",
      "compression": [],
      "lods": [],
      "collisionProxyIds": [],
      "tags": [
        "harness"
      ]
    },
    {
      "id": "voice:zh:0102Adv04_Ema002",
      "kind": "voice",
      "optimizedUri": "/harness/media/voice/zh/0102Adv04_Ema002.ogg",
      "format": "ogg",
      "compression": [],
      "lods": [],
      "collisionProxyIds": [],
      "tags": [
        "harness"
      ]
    },
    {
      "id": "voice:zh:0102Adv04_Ema003",
      "kind": "voice",
      "optimizedUri": "/harness/media/voice/zh/0102Adv04_Ema003.ogg",
      "format": "ogg",
      "compression": [],
      "lods": [],
      "collisionProxyIds": [],
      "tags": [
        "harness"
      ]
    },
    {
      "id": "voice:zh:0102Adv04_Ema004",
      "kind": "voice",
      "optimizedUri": "/harness/media/voice/zh/0102Adv04_Ema004.ogg",
      "format": "ogg",
      "compression": [],
      "lods": [],
      "collisionProxyIds": [],
      "tags": [
        "harness"
      ]
    },
    {
      "id": "voice:zh:0102Adv04_Margo001",
      "kind": "voice",
      "optimizedUri": "/harness/media/voice/zh/0102Adv04_Margo001.ogg",
      "format": "ogg",
      "compression": [],
      "lods": [],
      "collisionProxyIds": [],
      "tags": [
        "harness"
      ]
    },
    {
      "id": "voice:zh:0102Adv04_Margo002",
      "kind": "voice",
      "optimizedUri": "/harness/media/voice/zh/0102Adv04_Margo002.ogg",
      "format": "ogg",
      "compression": [],
      "lods": [],
      "collisionProxyIds": [],
      "tags": [
        "harness"
      ]
    },
    {
      "id": "voice:zh:0102Adv04_Margo003",
      "kind": "voice",
      "optimizedUri": "/harness/media/voice/zh/0102Adv04_Margo003.ogg",
      "format": "ogg",
      "compression": [],
      "lods": [],
      "collisionProxyIds": [],
      "tags": [
        "harness"
      ]
    },
    {
      "id": "voice:zh:0102Adv04_Margo004",
      "kind": "voice",
      "optimizedUri": "/harness/media/voice/zh/0102Adv04_Margo004.ogg",
      "format": "ogg",
      "compression": [],
      "lods": [],
      "collisionProxyIds": [],
      "tags": [
        "harness"
      ]
    },
    {
      "id": "voice:zh:0102Adv04_Sherry001",
      "kind": "voice",
      "optimizedUri": "/harness/media/voice/zh/0102Adv04_Sherry001.ogg",
      "format": "ogg",
      "compression": [],
      "lods": [],
      "collisionProxyIds": [],
      "tags": [
        "harness"
      ]
    },
    {
      "id": "voice:zh:0102Adv04_Sherry002",
      "kind": "voice",
      "optimizedUri": "/harness/media/voice/zh/0102Adv04_Sherry002.ogg",
      "format": "ogg",
      "compression": [],
      "lods": [],
      "collisionProxyIds": [],
      "tags": [
        "harness"
      ]
    },
    {
      "id": "voice:zh:0102Adv04_Sherry003",
      "kind": "voice",
      "optimizedUri": "/harness/media/voice/zh/0102Adv04_Sherry003.ogg",
      "format": "ogg",
      "compression": [],
      "lods": [],
      "collisionProxyIds": [],
      "tags": [
        "harness"
      ]
    },
    {
      "id": "voice:zh:0102Adv04_Sherry004",
      "kind": "voice",
      "optimizedUri": "/harness/media/voice/zh/0102Adv04_Sherry004.ogg",
      "format": "ogg",
      "compression": [],
      "lods": [],
      "collisionProxyIds": [],
      "tags": [
        "harness"
      ]
    },
    {
      "id": "voice:zh:voice_validation_0001",
      "kind": "voice",
      "optimizedUri": "/harness/media/voice/zh/voice_validation_0001.ogg",
      "format": "ogg",
      "compression": [],
      "lods": [],
      "collisionProxyIds": [],
      "tags": [
        "harness"
      ]
    }
  ] satisfies RuntimeAsset[];
